### ISSUE TITLE
Clean Up of SASS and CSS

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#101]
The use of CSS and SASS and they integration in the Frontend is a mess!
At the moment we have both CSS and SASS files. We HAVE to decide for one of them and I guess it is SASS:
 - All CSS files have to be removed from the repository
 - There is a SASS file under modules/common/sass. Is this used?
 - The SASS configuration should not be in the app folder, since all commands are executed in base directory. Move the config.rb up

**Comment by nadiapo** [comment]
- There is a SASS file under modules/common/sass. Is this used?
No, this has been removed

Regarding the rest of the ticket, we need to investigate how to configure SASS within node.js in order to compile on the fly css files

**Comment by FabiApfelkern** [comment]
@nadiapo @mmilaprat Can we put this into Sprint 3?

**Comment by nadiapo** [comment]
we prefer to focus on other design tasks and leave this task for later

**Comment by FabiApfelkern** [comment]
Can you please reconsider? I think it is very important to have this cleaned up. Because its not just Atos which is working with the styles and so. We all have to extend the frontend and we need a clean way to do this. I am personally not sure where to modify styles at the moment. Thank you!

**Comment by nadiapo** [comment]
We will try to have it but we cannot commit to have it done by this sprint.

**Comment by FabiApfelkern** [comment]
Thank you!

**Comment by FabiApfelkern** [comment]
I think is should be possible in Sprint 4

**Comment by mmilaprat** [comment]
close.
pul request related # 155
