### ISSUE TITLE
Portal main colours

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#108]
The brown color in the portal combined with grey looks good (at least better than green), but it would be good to see several other possible compibantions with grey: dark orange, dark blue, etc. So, we could make the optimal choice

**Comment by nadiapo** [comment]
Decided on maintaining the menu grey and provide the main colour in dark orange.
Grey text should be made slightly darker.
Need to try to make menu tab a little smaller in hight
Add a new menu item, "Discussions", before the Request menu item

**Comment by nadiapo** [comment]
done
