### ISSUE TITLE
Chart "zooming"

### ISSUE THREAD

**Issue by nadiapo** [policycompass/policycompass#112]
Look into the possibility to "zoom" into specific parts of visualisations by changing the start and/or end date of visualisations.
When user selects datasets, he must be able to avoid a period of time from the begining or/and from the end.

**Comment by mmilaprat** [comment]
Is not a zoom. The  idea is to be ablle to change the start date and the end date of charts (not only line charts).

When user selects datasets, he must be able to avoid a periood of time from the begining or/and from the end.

**Comment by mmilaprat** [comment]
first version is available
