### ISSUE TITLE
FCM needs to expose an API that lists FCMs based on one or more indicators

### ISSUE THREAD

**Issue by nadiapo** [policycompass/policycompass#114]

**Comment by belalakbar** [comment]
@nadiapo 
here is the api 
https://frontend-stage.policycompass.eu/api/v1/fcmmanager/metrics/2
you can use

**Comment by mmilaprat** [comment]
In the visualisation we need to list the FCM linked with a visualisation.

In the visualisation we work with "datasets" each dataset has "individuals".

The api you provide list the FCM related with a metric. How we can get the list of FCM related with a dataset or an individual?

**Comment by belalakbar** [comment]
The FCM which will use the given metric. because FCM is connect with the metric.

**Comment by mmilaprat** [comment]
@FabiApfelkern . Do yo know how we can get the lis of metrics linked with dataset?

Semantic search can get the list of metrics that has a dataset or an individual?

**Comment by FabiApfelkern** [comment]
I am not sure if @belalakbar really means Metric or Dataset.

**Comment by belalakbar** [comment]
i mean metric because currently connected to metric.

**Comment by FabiApfelkern** [comment]
@belalakbar Move this to Sprint 5? Who is responsible here?

**Comment by nadiapo** [comment]
@belalakbar can you please expose an API that lists FCMs based on a list of datasets or a list o individuals?

**Comment by belalakbar** [comment]
move this to sprint 5

**Comment by belalakbar** [comment]
@mmilaprat The following api's has been implemented. You need to again setup the FCMManager service.
https://frontend-stage.policycompass.eu/api/v1/fcmmanager/datasets/{id}
https://frontend-stage.policycompass.eu/api/v1/fcmmanager/individuals/{id}

**Comment by mmilaprat** [comment]
@belalakbar , I checked the FCM API in the different environments and:

alpha:
https://alpha.policycompass.eu/api/v1/fcmmanager/models -> works
https://alpha.policycompass.eu/api/v1/fcmmanager/datasets -> Not works, probably becuse is not implemented
https://alpha.policycompass.eu/api/v1/fcmmanager/individuals -> Not works, probably becuse is not implemented

stage:
https://services-stage.policycompass.eu/api/v1/fcmmanager/models ->the fcm is not working, probalby is not in this server.

the above links, didn't work.

You know when the FCM API will be available in one of the environments?

**Comment by aquinas9** [comment]
We will close this after the server is updated.

**Comment by mmilaprat** [comment]
@belalakbar , If we wish to get the FCM related with more than 1 dataset or individual, can we pass more than one id to the API?

Example:
https://frontend-stage.policycompass.eu/api/v1/fcmmanager/datasets/1,3,6
https://frontend-stage.policycompass.eu/api/v1/fcmmanager/individuals/2,5,7

**Comment by mmilaprat** [comment]
@belalakbar , can you attach an example of the jsons that I can recover from these APIS?

**Comment by mmilaprat** [comment]
Do you have any idea of when these APIs will be working into the alpha or stage environment?
