### ISSUE TITLE
Instatiate an FCM from a specific visualisation based on the indicators

### ISSUE THREAD

**Issue by nadiapo** [policycompass/policycompass#115]
Need to be able to instatiate an FCM from a visualisation, passing the list of indicators from the visualisation. The FCM need to prepopulate the concepts based on the list of indicators passed.

**Comment by belalakbar** [comment]
@nadiapo 
can you please give elaborate a bit more.

**Comment by nadiapo** [comment]
@belalakbar this is what we agreed in the meeting in Cambridge. From a visualisation, when we click the "Create Casual Model" button we will go to the FCM page with concepts pre-populated based on the indicators of the visualisation. The list of indicators will be passed from the visualisations screen when clicking the button.
I hope it is a bit more clear now.

**Comment by belalakbar** [comment]
@nadiapo How can you pass the list of indicators?

**Comment by belalakbar** [comment]
@mmilaprat for this function can you please tell me who I will get the list of the indicators to pre-populate the concepts in FCM editor.

**Comment by mmilaprat** [comment]
probably the best solution is to pass the list of the indicators in the url when we click over the link "Create Causal Model" that appears into the visualisation detail page.

something like this:
/app/#!/models/create?indicators=1,2,7,32

something like this is used to load datasets into the visualisation when users click over the link "Visulise" that appears into the dataset main page.

In this case the url is like this:
/app/#!/visualizations/create/?datasets=11

**Comment by aquinas9** [comment]
We need to make more clear for further development for this.

The problem is what should be the concept when user go into the FCM manager from visualisation. 

Indicator is different from the concept in FCM. 

But reverse procedure seems quite simple (FCM -> Visualisation). Maybe all the data sets which are related to the concept can be passed to the create visualisation.

**Comment by cbotsikas** [comment]
/app/#!/models/create?indicators=1&indicators=2&indicators=7&indicators=32 would be proper. If visualization has this list, it can also use /app/#!/models/create?visualization=15 and grab the list using visualization api

**Comment by cbotsikas** [comment]
```Indicator is different from the concept in FCM.```
Indeed, this is an issue. It's also not clear to me. 
How are the indicators linked with a visualization and where does the FCM use them.

**Comment by aquinas9** [comment]
@cbotsikas @belalakbar @YuriGlickman 
I think we need more discussion on this with Yuri. 
We can discuss it in next telco.

**Comment by YuriGlickman** [comment]
I think Nadia and Miquel has explained it, but I will try to add a few details:
1. As Nadia wrote "From a visualisation, when we click the "Create Casual Model" button we will go to the FCM page with concepts pre-populated based on the indicators of the visualisation. The list of indicators will be passed from the visualisations screen when clicking the button."
2. Indicators are differerent from Concepts in FCM, but they are similar. Both of them have a title and a description. The weight can be set to "0".
3. We are visualising datasets, but for each dataset there is an indicator associated with it.

**Comment by mmilaprat** [comment]
I'm going to update the code of the "Create Causal Model" button that appears into the visualisation detail page to create links like this:

app/#!/models/create?indicators=208&indicators=75&indicators=82

**Comment by belalakbar** [comment]
How you pass the indicator to create model?

**Comment by mmilaprat** [comment]
I added the list of indicatord in the url

app/#!/models/create?indicators=4&indicators=1&indicators=3

**Comment by FabiApfelkern** [comment]
@mohammedbahja Do you want to move this to Sprint 9?

**Comment by cbotsikas** [comment]
FCM implementation: https://github.com/policycompass/policycompass/issues/458
