### ISSUE TITLE
Trigger stage rebuild on travis success

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#125]
If travis passes, it should trigger a rebuild on the staging server.

In Cambridge, we talked about adding a special route which calls the rebuild, which can also be called manually.

**Comment by FabiApfelkern** [comment]
@nidico who is responsible for this?

**Comment by nidico** [comment]
LIQD / @slomo. However we wanted to talk about the physical location of the server beforehand, as we would do it differently at LIQD (SSH) than at FOKUS (HTTPS?). However we didn't talk about that yet. We should do that once the relevant persons are back from holidays.

**Comment by FabiApfelkern** [comment]
Sorry, I haven't told you. I talked to Yuri and he thinks we should keep everything as it is with the servers. And unfortunately we cannot give you root access due to central Fraunhofer security policy. Is it still possible?

**Comment by nidico** [comment]
> Is it still possible?

I guess. But we'll need another service running behind nginx as nginx doesn't provide simple CGI (at least that's what @slomo said at some point). SSH would be much easier...

> I talked to Yuri and he thinks we should keep everything as it is with the servers.

Let's discuss this together when @slomo and Yuri are back.

**Comment by nidico** [comment]
This is not very urgent. We'll reconsider for year 3.

**Comment by nidico** [comment]
Duplicate of #23.
