### ISSUE TITLE
Dedicated login & register pages

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#126]

**Comment by FabiApfelkern** [comment]
Can we have this in Sprint 3?

**Comment by nidico** [comment]
I'll tell today.

**Comment by FabiApfelkern** [comment]
Any decision here?

**Comment by nidico** [comment]
I wanted to look at the size while implementing the #121, but I moved that task to ~~my holidays~~ next week.

Well let's put it in sprint 3.
