### ISSUE TITLE
Set Body Temp Path of nginx

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#128]
There where some API calls which failed without an obvious reason. Most notable saving large FCM graphs and uploading files to the Metrics Manager. I debugged it and figured out that nginx had no access rights to its body temp path which is apparently needed for handling large requests. So I created a directory in the policycompass home folder and set this directory as client_body_temp_path in the nginx.conf (only on stage).
I just fixed it live on the server, so it still need to be commited and configured properly within the repo.

**Comment by FabiApfelkern** [comment]
@slomo Can you do this please in Sprint 2?

**Comment by nidico** [comment]
Fixed with #137.
