### ISSUE TITLE
Metrics Manager API

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#143]
The New Metrics Manager needs its own API. 
@nidico I think this should happen in Sprint 3!

**Comment by nidico** [comment]
Realistically not, due to holidays, so this will be done in sprint 4. This is not too bad because no other component depends on the metrics manager.

**Comment by nidico** [comment]
For the reference, the state of the API as of D2.2 can be read here:

    https://github.com/policycompass/policycompass/wiki/Metrics-Manager-API

**Comment by nidico** [comment]
We updated the document. This is pretty much done, however will change during implementation.
