### ISSUE TITLE
FCM Manager Postgresql Migration Process

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#148]
We do need a way to migrate the Database, when the models change. It is not practical anymore to delete the database anytime. In my opinion this cannot be solved directly with Hibernate. You probably need SQL migrations scripts.
@belalakbar Can you do this in Sprint 3.

**Comment by belalakbar** [comment]
What does mean by migrate the Database? Actually I made some changes in the database structure according to new functionalities. So, we need to update these changes on the live server.

If you mean that existing data should be save before remove then definitely we need to write script to save the data and again restore the data.

**Comment by mmilaprat** [comment]
Hi,
for the visualisation can be a problem if we need to migrate content from "the old" database structure to the "new one".

The new visualisation functionalities works with datasets, not with metrics.

**Comment by FabiApfelkern** [comment]
Yes, we need a way to migrate your database scheme and keep existing data. This is usually done with SQL migration scripts, which transform the database from one state into another.

**Comment by FabiApfelkern** [comment]
@mmilaprat This is just about FCM Hibernate. What do you mean with Visualisation here?

**Comment by mmilaprat** [comment]
I mean. a migration from visualisations is needed? At this moment it seems that there isn't any "real" chart and we don't know the possible relation between the existing metrics and the new datasets.

**Comment by mmilaprat** [comment]
forget my comments. 

This is just for FCM.

**Comment by FabiApfelkern** [comment]
Ok, what about it? Can you put it in Sprint 3? Thanks!

**Comment by FabiApfelkern** [comment]
I guess this is a misunderstanding. It's not about how to load data into the database. It is about the migration of the database schema. At the moment you change your models, e.g. adding or removing a property, it is necessary to delete and re-imitate the tables of the database. This is not practical, since all data is deleted.

**Comment by belalakbar** [comment]
So I need to make SQL migrations scripts that can be used to migrate the old database schema into new database schema.

**Comment by FabiApfelkern** [comment]
Exactly! Thats what I proposed in this issue. But you can also do some research what the official Hibernate way is to do that.

**Comment by belalakbar** [comment]
thanks

**Comment by belalakbar** [comment]
I checked Hibernate will automatically did this one, so no need any script.

**Comment by FabiApfelkern** [comment]
Can you please provide a link to the documentation about this Hibernate feature? The last time I used Hibernate this was not possible. Sometimes it can migrate automatically, but very often it cannot. Es specially when you rename fields or add not-null fields.

**Comment by belalakbar** [comment]
Yes you are right, it cannot work with rename fields or add not-null fields. but next we will add nullable fields so that it can be add in existing table.

**Comment by FabiApfelkern** [comment]
I will close this, since you think it is not necessary. I hope you are right.
