### ISSUE TITLE
Remove "Scale" from the FCM's "Add Concept" dialogue

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#150]
Remove the "Scale" filed from the FCM's "Add Concept" dialogue to advanced options (or different place).

The Description field has to be optional. In many cases it is not needed

**Comment by aquinas9** [comment]
As we described in other ticket, maybe this option will be moved to simulation stage. 
Fundametally, we will unifiy the sclae for same model. Setting different scale for each conepts will be an advnaced option.

**Comment by YuriGlickman** [comment]
Still pending: "The Description field has to be optional. In many cases it is not needed"

**Comment by aquinas9** [comment]
We need the description for concept for the recommendation in next year. But we will change this filed as optional.
