### ISSUE TITLE
Linkage between Concepts and Indicators

### ISSUE THREAD

**Issue by aquinas9** [policycompass/policycompass#151]
Concepts will be linked to the indicators that have concrete datasets. 
Need to develop Interface to search relevant indicators

**Comment by YuriGlickman** [comment]
I tried to add metrics to concepts, but after saving the model they are always gone. please check.

**Comment by aquinas9** [comment]
We add the metric to obtain the data from metric to calculate the value of concept. We need to save the calculated value not metric it self. User maybe add different metric for same concept and new will value will be calculated for concept. 

However when we will add metric it will automatically generate an API for visualization and metric.
We will do this in next sprint(sprint 4)
