### ISSUE TITLE
Creat Association dialogue

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#152]
1) Rename the window name from "Association" to "Create Association"
2) Add a field with a drop dow list for weight:
- Very strong positive
- Strong positive
- Weak positive 
- Very week positive
- Very week negative
- Weak negative
- Strong negative
- Very strong negative

or something similar with more or less predefined values. I think 4 for each direction should be enough
1.0 Very strong
0.75 Strong
0.5 Weak
0.25 Very Week

In general, I think we should use more predefined labels instead of numbers in the FCM's GUI

**Comment by YuriGlickman** [comment]
a possibility to set or edit weight manualy is still missing (see point 2 in the original issue). In many cases users will not use real data for FCM. They should be able to set or change the weights for associations.

**Comment by aquinas9** [comment]
"a possibility to set or edit weight manualy is still missing (see point 2 in the original issue). In many cases users will not use real data for FCM. They should be able to set or change the weights for associations."
=> We will discuss about this more with Habin and Bilal. After that, we will create new issues on this. Originally, we understood your message as to remove the numeric editing function and put into the combo-box.

"I see that you added this possibility in the simulation parameters tab, but it is not enough. It should be possible in the association Create and Edit dialogues"

=> As we said in the previous meeting, We thought that the simulation stage should be separated from from modelling and it was the result of discussion with Habin and Bilal. We will review your comment again with them.
