### ISSUE TITLE
Create FCM thumbnail

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#159]

**Comment by belalakbar** [comment]
Can you give a bit more description?

**Comment by cbotsikas** [comment]
@belalakbar as we discussed on previous meetings, we need a static image representation of each FCM model so that we could use it for the social media interaction.This procedure is also needed for Visualization (https://github.com/policycompass/policycompass/issues/158) where we already have a prototype in NodeJS. using a headless browser to capture the image. We might end up using the same technique with FCM graphs, although it's not tested yet, or if you have anything to suggest, please do so. Apart from the FCM graph, do you think it makes sense to have a different image representation for the FCM?

**Comment by FabiApfelkern** [comment]
@belalakbar @aquinas9 This needs to addressed in Sprint 5.

**Comment by cbotsikas** [comment]
This is part of the social media share integration

**Comment by mohammedbahja** [comment]
@cbotsikas many thanks for this. Did anybody make it for the other components yet ?

**Comment by cbotsikas** [comment]
closing in favor of https://github.com/policycompass/policycompass/issues/465
