### ISSUE TITLE
Make creates wrong symlinks on ubuntu

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#163]
Due to a bug in coreutils, which got fixed in 8.22 [(ln --relative now updates existing symlinks correctly)](https://savannah.gnu.org/forum/forum.php?forum_id=7815), the makefile creates wrong symbolic links (e.g. `etc/nginx.conf`, `policycompass-services/config/settings.py`) on every second run.

**Comment by FabiApfelkern** [comment]
@nidico Can we fix this until next week, so deployment gets easier.

**Comment by nidico** [comment]
@slomo: can you please fix this when you're back (i.e. next week)?

**Comment by FabiApfelkern** [comment]
@nidico But we should put it in Sprint 4?

**Comment by nidico** [comment]
Ok.

**Comment by slomo** [comment]
As usual there are two ways to fix this:

* Update ubuntu or update coreutils only
* Introduce workaround where files are removed before linking

Since I am trying to keep this compatible with a out-of-the-box Ubuntu LTS I will implement the second option
