### ISSUE TITLE
I Want To wizard leads to page reload. 

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#174]
To start a I Want To wizard a link with a trailing slash is used. This leads to a complete reload of the page. This is not desired in a single page application. I understand this was done to force a reload of the wizard directive. But they shoud be another way. 

https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/common/directives/wizard.js#L175

**Comment by mmilaprat** [comment]
resolved
