### ISSUE TITLE
Increase Z-Index of Submenu

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#179]
The Z-index of the main submenu needs to be increased, as some third-party libraries have higher values. It is currently set to 99.

**Comment by FabiApfelkern** [comment]
@mmilaprat @nadiapo Can we have this in Sprint 5?

**Comment by nadiapo** [comment]
@FabiApfelkern @mmilaprat told me that you have done some modifications in respect. What remains to be done in this issue?

**Comment by FabiApfelkern** [comment]
Yes, a small thing.I just implemented a workaround in my dataset.css. But this needs at some general place.
