### ISSUE TITLE
Automatic weight and fuzzy value calculation using data

### ISSUE THREAD

**Issue by aquinas9** [policycompass/policycompass#181]
We will discuss with Fabian regarding how we can get data we want.. 

Now we can't select specific data from metric. 

For example, some metric have data for both spain and germany. 

But for the calculation, we need to be able to select one of them..

**Comment by FabiApfelkern** [comment]
@aquinas9 What about this? Move to Sprint 5?

**Comment by belalakbar** [comment]
https://github.com/policycompass/policycompass-frontend/pull/232

**Comment by FabiApfelkern** [comment]
Create a new one.

**Comment by FabiApfelkern** [comment]
@mohammedbahja Do you want to move this to Sprint 9?

**Comment by FabiApfelkern** [comment]
@mohammedbahja Any comments on this one?

**Comment by mohammedbahja** [comment]
sub issues:
policycompass/policycompass/issues/575
