### ISSUE TITLE
converting simulation result into linguistic measure 

### ISSUE THREAD

**Issue by aquinas9** [policycompass/policycompass#182]
Now we only can get the result as a floating point between 0 and 1. 
In this sprint, we will set up the function supporting linguistic presentation of simulation result.

**Comment by FabiApfelkern** [comment]
@aquinas9 What about this? Move to Sprint 5?

**Comment by belalakbar** [comment]
this done and need to be closed.

**Comment by FabiApfelkern** [comment]
You could close it by yourself.
