### ISSUE TITLE
Embedded Adhocracy should be in the same language as PolicyCompass

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#185]
Currently PolicyCompass is always English.

**Comment by FabiApfelkern** [comment]
The dedicated login page is still in German: https://frontend-stage.policycompass.eu/app/#!/login

**Comment by FabiApfelkern** [comment]
And the confirmation page presented, when activating the account is also in German.

**Comment by nidico** [comment]
I only did this for the discussion part of Adhocracy. The rest I will do together with the open auth tasks (#126 etc).
