### ISSUE TITLE
Visualisations Color-Picker not Cross-Browser compatible 

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#186]
The Color-Picker should work on all common Browsers. The screenshot was taken with Safari. In general I think the color picker should be made with purely JavaScript and not with an HTML5 element. So it will look the same in every browser. And I think it is not needed to choose between all RGB colors. It might be enough to have slider with 256 color or so. What do you think?

<img width="1179" alt="screen shot 2015-08-27 at 15 57 55" src="https://cloud.githubusercontent.com/assets/1488424/9541632/6db1bce4-4d6a-11e5-8f0b-71f5630937a3.png">

**Comment by mmilaprat** [comment]
ok. I'm going to try to find a better solution for the colour picker.

**Comment by mmilaprat** [comment]
I'm tinking to use this directive:

http://ruhley.github.io/angular-color-picker/

To use it I need to update the angular version from 1.2.27 to 1.3.18. Do you think that this update can be a problem for the platform?

**Comment by FabiApfelkern** [comment]
I tried once to update to a newer version of Angular and it caused a lot of problems, because we have so many dependencies. We really should update some day but I think now is not the time. I think we should to this after year 2, so in December. Because we have to migrate the dependencies, test everything and so on. If you want to do this know, go ahead. :)
But you can try to use this directive with 1.2.27. I may work anyways.

**Comment by mmilaprat** [comment]
close.
pul request related # 158
