### ISSUE TITLE
rotate data in "Upload Datasets" (Step 1)

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#189]
If you try to "rotate data" with something like this:

1a	"empty cell"	1c
2a	2b	2c
3a	3b	3c

a javascript error appears (Cannot read property 'push' of undefined)

![error_rotate_dataset](https://cloud.githubusercontent.com/assets/6602727/9603599/016504a6-50b2-11e5-8477-41832ac2c496.png)

**Comment by FabiApfelkern** [comment]
@mmilaprat  I have still problems to recreate that error. Can you please send me a CSV file which produces that error?

**Comment by mmilaprat** [comment]
Is when the data input is manually and the cell 1B is empty.
