### ISSUE TITLE
Error popup when creating visualisation from dataset view

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#190]
If you want to create a Visualization directly from a dataset view you get an error popup "arrayExtraColumnsMetric is undefined"

Example:
https://alpha.policycompass.eu/app/#!/visualizations/create/?datasets=1

**Comment by FabiApfelkern** [comment]
In the current master error is gone but now no graph is displayed. I have to refresh the entire page to see it.

**Comment by FabiApfelkern** [comment]
Please check the new error: https://frontend-stage.policycompass.eu/app/#!/visualizations/create/?datasets=1

**Comment by mmilaprat** [comment]
I'm checking it
