### ISSUE TITLE
Individual selection not working

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#191]
The selection or deselection of an individual of a dataset has no effect to the visualization.

**Comment by mmilaprat** [comment]
I think that this is due to the fact that the dataset manager don't have the filter by individual

**Comment by FabiApfelkern** [comment]
You think? What have you implemented? :) I think in general we should consider not to show functions in the frontend which are not ready. Or just disable them with ng-disabled. Otherwise it might confuses the user.

**Comment by mmilaprat** [comment]
I'm working to change the way to filter individuals

**Comment by FabiApfelkern** [comment]
You don't have to do this. I will implemented in the backend anyway. There is already a ticket for this: https://github.com/policycompass/policycompass/issues/198
You should work on your Sprint 4 tickets: https://github.com/policycompass/policycompass/issues?q=is%3Aopen+is%3Aissue+assignee%3Ammilaprat+milestone%3A%22Sprint+4%22

**Comment by mmilaprat** [comment]
I know. But there is some problems with update actual version of maps and individauls that seem to be related

**Comment by mmilaprat** [comment]
close.
pul request related # 154
