### ISSUE TITLE
Rename Delete Buttons in Visualization

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#194]
I think the Button "Delete" for Datasets and Events in the Visualization Frontend should have a different name. I am always confused if I delete the Dataset or just remove it from the Visualization.

**Comment by mmilaprat** [comment]
"Unlink" is better?

**Comment by FabiApfelkern** [comment]
I am not sure. What about "Remove".

**Comment by mmilaprat** [comment]
ok, I will update the labels with "Remove"

**Comment by FabiApfelkern** [comment]
Its just a proposal. You can talk to Nadia first maybe. 
And by the way you don't have to work on every ticket immediately.... :)

**Comment by mmilaprat** [comment]
close.
pul request related # 154
