### ISSUE TITLE
Description for Events 

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#195]
Is there a particular reason why a user can enter a description for a linked event?

**Comment by mmilaprat** [comment]
The data that appears in the div of an event linked with a visualisation onmouse over is:
Title
Start & end date
Description

The idea of the description is to give more information about the event, can be the description of the event (data used by default when you try to link events) or any custom text that tries to explain what means the event in a chart.

**Comment by FabiApfelkern** [comment]
Ok. I understand. Thanks!
