### ISSUE TITLE
Warning or Filter Events which are not within time range

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#196]
It is possible to link events which are not within the time range of the Visualization. The user gets no feedback. Either this is not allowed at all or the user gets some kind of warning.

**Comment by mmilaprat** [comment]
yes.
There is 2 ways to link evets with visualisations.

1rst. If you click over the line chart, the "start date" and "end date" fields are filled with the start and end date of the chart. (You can change this data)

2nd. In the tab "Historical Events" there is the button "Add historical event". With this button the fields Start and end date are not filled. (But this only works if you don't click over the chart previosly, I will check why)

**Comment by FabiApfelkern** [comment]
But still, the user is able to add an event outside the range. This should not be possible.

**Comment by FabiApfelkern** [comment]
@mmilaprat Something about this? Can we get this warning?

**Comment by mmilaprat** [comment]
I'm working on it.

**Comment by FabiApfelkern** [comment]
@mmilaprat Now in the current master it is not possible anymore to select an event outside the range anymore. Is that right?

**Comment by mmilaprat** [comment]
Theorically yes!!

**Comment by FabiApfelkern** [comment]
Theoretically?

**Comment by mmilaprat** [comment]
I update the modal window to use the start and end date of the dataset selected as filters. I test it and works.

**Comment by FabiApfelkern** [comment]
Yes it works. I just was wondering if it was on purpose.
