### ISSUE TITLE
General Layout and Concept for Viewing Entities

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#200]
I noticed that basically all of our entities consist of metadata and the entity itself. E.g. metadata + dataset, metadata + visualization, metadata + fcm,  and so on. But we have no general layout for viewing such entities. Everybody is implementing its own view layout. 

https://alpha.policycompass.eu/app/#!/models/1
https://alpha.policycompass.eu/app/#!/datasets/1
https://alpha.policycompass.eu/app/#!/events/1

In my opinion we should have guideline and template for such views. Some concept how to present the metadata and where to put the actual data. This will harmonize the look and feel and reduces work for everybody. Personally I always have problems with presenting all the metadata in proper and clear way. What do you think?

**Comment by FabiApfelkern** [comment]
It would be great to take care of the fact that Adhocracy has to be very small. https://github.com/policycompass/policycompass/issues/89 So fill the gab with some content.

**Comment by nidico** [comment]
It's not that Adhocracy has to be very small. It's a general rule that text blocks shouldn't have much more than 12 words per line (or something like that, I'm not a UX person).

**Comment by FabiApfelkern** [comment]
I don't want to argue about it, I'm also not an UX person, but if thats true literally nobody is doing it like this. (My first line has 23 words). But it's okay, we just have to deal with it.

**Comment by FabiApfelkern** [comment]
@nadiapo Do you think we can come up with something in Sprint 5?

**Comment by nadiapo** [comment]
Yes

**Comment by FabiApfelkern** [comment]
I will close this for now and we will review our design next project year. Some improvements were already made.
