### ISSUE TITLE
Percentage Mode is not clear

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#202]
I have to admit I am not sure what the "Show as %" exactly does. From which values is the percental value taken? In this Example [1], why do I get a scale up to 350 in percentage mode? And the axis still says "People" as unit. Can you please explain this function for me?

[1] https://alpha.policycompass.eu/app/#!/visualizations/create/?datasets=1

**Comment by mmilaprat** [comment]
Show as % sets the first value of the dataset to 0. Takes the inital value of the dataset as reference and then calculates the % of the folloging values.

**Comment by FabiApfelkern** [comment]
Thank you. I will think about it. In my opinion this is not clear to the user.

**Comment by FabiApfelkern** [comment]
I think we leave it. But can you change the axis label to "Percentage" instead of the original unit?

**Comment by mmilaprat** [comment]
ok, I'll update it.
When the chart will be plotted as percentage the Y label will be "As % (original label)"
