### ISSUE TITLE
Search historical events by country

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#204]
We need to search historical events by country. We will use it in visualisations to recomend events.

Related with issue #51 (policycompass/policycompass/issues/51)

**Comment by mmilaprat** [comment]
As @FabiApfelkern suggests we can use elastic search to find events but I suppose that geoLocation is not the final name for the field where country will be stored, and in the events-manager api the "country" field doesn't appear.

**Comment by FabiApfelkern** [comment]
I suppose we have to adjust in to our conventions. But please discuss it with @almey. But for sure we should do it with Elastic Search.

**Comment by mmilaprat** [comment]
Ok, I'll use elastic search. 

@almey can you tell me the exact name for the country field?

**Comment by almey** [comment]
the field is called 'geoLocation' in the events model

**Comment by mmilaprat** [comment]
then the actual geoLocation field data (lat, lng) will be replaced by a country id?

**Comment by FabiApfelkern** [comment]
@mmilaprat Do you need this for Sprint 7?

**Comment by mmilaprat** [comment]
I use elastic search to find events related with a country.

I use queries like:


query = {
                    "filtered": {
                        "filter": {
                            "terms": {
                                "geoLocation": [array ids individuals]
                            }
                        }
                    }
                };

**Comment by FabiApfelkern** [comment]
Yo, our are fine for now?

**Comment by FabiApfelkern** [comment]
@mmilaprat Is this still an issue? I lost track.

**Comment by mmilaprat** [comment]
I checked the content of events in my local database.

The content of the "geoLocation" field is a "string", in my case I have values like:
null
a lat and lng like: 52.521332, 13.342037
a string like : Germany

when I do the query I search by the idividual id of the country (the id in our db)

I checked the web form to create an event manualy and the field "Geolocation" is a string.

**Comment by FabiApfelkern** [comment]
I understand. So we just need to change the data type of the field and link it to reference pool then?

**Comment by mmilaprat** [comment]
I don't know which is the better solution. 

One is to "close" the "geoLocation" field into the events form to the correct list of countries (individuals) of our database.

Another is to forget the serach by country.

How the import functionality works? because probably we import some location data

**Comment by FabiApfelkern** [comment]
I'm not sure I understand you correctly, sorry. :)  Are you using this field actively?

**Comment by mmilaprat** [comment]
I use the field but as this does not store the id of the country, the search never find data.

**Comment by FabiApfelkern** [comment]
@cueneythizli Please do this. Just add an additional field spatials like for Datasets.
