### ISSUE TITLE
Allow to install on Ubuntu >= 14.10 and Debian stable

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#206]
There are two issues when trying to install PCompass on Ubuntu >= 14.10 or Debian > stable (Jessie):

- Postgres is now at 9.4, therefore `POSTGRES_BIN_PATH` is wrong in `Makefile`
- `leiningen` is not available.

The first issue can be fixed through some detection logic in the Makefile.

What to do about the second issue? Leiningen is needed in order to install carneades.

**Comment by FabiApfelkern** [comment]
The Clojure-based Carneades version is discontinued. There is already the new version written in Go available [1]. We are working on a frontend for this. I confident that it will be ready for the review. 

[1] https://github.com/carneades/carneades-4

**Comment by nidico** [comment]
We just removed the unneeded package dependency, which already resolved this issue. So carneades 3 can still be installed. We can exchange that once we have carneades 4 in place.
