### ISSUE TITLE
Better JSON Styling in API Documentation

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#21]
We should have a great JSON formating in our documentation. I corrected one of the Visualisation examples (https://github.com/policycompass/policycompass/wiki/Visualisation-manager). I used this page http://jsbeautifier.org/ and a JSON markdown tag for it.

**Comment by mmilaprat** [comment]
Good idea. I just updated the rest of JSONs.

**Comment by FabiApfelkern** [comment]
Cool! Thank you.
