### ISSUE TITLE
Better logout UI

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#216]
In order to log out, you need to click on the user in the main header, then on logout and then on logout in the embedded iframe.

Two possible improvements:

Ideally: skip the last click (might not be trivial though at the moment)

At least:

- [x] make sure the subheader disappears after clicking on *logout* in it, so that the actual (embedded) logout button is visible
- [x] make it clear in the UI that you have to click that inner link as well.

**Comment by FabiApfelkern** [comment]
@nidico It would be great to have an Assignee here.

**Comment by nidico** [comment]
I'm fine with assigning me here, as it's clear that I'll do it. However in my opinion this isn't strictly necessary, as the *AUTH* label clearly indicates that LIQD is responsible, but we might still need to sort out, who at LIQD. No problem in this case though.

**Comment by nidico** [comment]
This is done as much as can easily be done without major extension of AdhocracySDK.
