### ISSUE TITLE
Request menu item

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#220]
the top menu option "request" can be disabled until have valid content.

for me it's better to disable the option than the text "coming soon"

**Comment by FabiApfelkern** [comment]
@nidico I'm not sure. Is Liqd responsible for the request service?

**Comment by nidico** [comment]
> Is Liqd responsible for the request service?

Yes.

> I'm not sure.

It doesn't matter for me. I'd leave it as a placeholder for now. If - for some reason - we wouldn't have the request service for the review, we should remove it until then.

**Comment by nidico** [comment]
Request service is ready.
