### ISSUE TITLE
Create an argument map from dataset item

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#222]
If I click over the link "Create Argument Map" I get an empty page.

https://alpha.policycompass.eu/app/#!/datasets/1

**Comment by FabiApfelkern** [comment]
Carneades is not integreated properly at the moment. This is known.

**Comment by FabiApfelkern** [comment]
We agreed to disable the button for now.

**Comment by FabiApfelkern** [comment]
Workaround merged. Removed from sprint.

**Comment by mohammedbahja** [comment]
@FabiApfelkern do we need this for FCM ?
