### ISSUE TITLE
bottom menu

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#229]
In the bottom menu there are option that don't "work" (Privacy, Contact, Terms of Use)

We must delete from the menu or create a pager with the contetn "comming soon"

**Comment by mmilaprat** [comment]
How we proceed with this? I must delete the links Privacy, Contact, Terms of Use ?

**Comment by cbotsikas** [comment]
This is related to https://github.com/policycompass/policycompass/issues/232 
@YuriGlickman how should we proceed?
