### ISSUE TITLE
Policycompass privacy & terms and conditions.

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#232]
On the footer of the app there are two inactive links for the "Privacy" and the "Terms of Use" as well at the registration page, there is this required "I accept the terms and conditions." without stating the terms and conditions. I guess, all those are needed before releasing a public version.

**Comment by cbotsikas** [comment]
@YuriGlickman @nidico is there anything planed for those texts?

**Comment by YuriGlickman** [comment]
I will take care about it. Thank you Christos

**Comment by nidico** [comment]
@YuriGlickman: If we have a site to link to we will set that up in the auth service configuration.

**Comment by nidico** [comment]
@YuriGlickman - any news here?

**Comment by FabiApfelkern** [comment]
@YuriGlickman Can you give us an update here?

**Comment by FabiApfelkern** [comment]
@YuriGlickman We still need this, do we?

**Comment by YuriGlickman** [comment]
I think we need only the Imprint section. We should take this one as a basis and update it:
https://www.fokus.fraunhofer.de/imprint

**Comment by mmilaprat** [comment]
but this imprint content is not equal that the one we have in "Publising Notes"?

https://frontend-stage.policycompass.eu/app/#!/publishingNotes

**Comment by YuriGlickman** [comment]
It is, but we have to update the text and it has to be called Imprint. I think it is legal requirement in Germany and because the portal is hosted in Germany it may create us some problems.
I will update the text right now and send it to Fabian.
