### ISSUE TITLE
Canceling registration or login leads to a blank page

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#233]
On both pages there is a CANCEL link at the bottom which leads to a blank page.

An expected behaviour would be to land on the previous page, but i think this is not needed.

I propose to remove it. If the user wants to cancel the registration or login process, he can always navigate away using the top menu or the back feature on his browser.

**Comment by FabiApfelkern** [comment]
@slomo @MagdaN Can that be done?

**Comment by FabiApfelkern** [comment]
Remove the button!

**Comment by slomo** [comment]
Fixed
