### ISSUE TITLE
Acceptance tests for complete "happy flow"

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#24]
We should cover the "happy flow" frontend clickthrough for all modules. We can do this with actual running backends.

LIQD is using [Protractor](https://angular.github.io/protractor/#/) now for Adhocracy and it's working better than everything else so far.

**Comment by FabiApfelkern** [comment]
@nidico Is it realistic that we will get this ever?

**Comment by nidico** [comment]
Year 3...
