### ISSUE TITLE
Control symbols in FCM are gone

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#242]
In the latest deployed version the control symbols from the left corner are missing. Please check what happend and reassign ticket to another person if needed.
![control symbols](https://cloud.githubusercontent.com/assets/8254248/9838862/35bae7ce-5a68-11e5-9f75-d2ee0b37f2c6.jpg)

**Comment by FabiApfelkern** [comment]
@belalakbar Can you please check?

**Comment by belalakbar** [comment]
@FabiApfelkern these symbols define in the cytoscape.js-panzoom.css. Now, how can I add this css file.

**Comment by mmilaprat** [comment]
all the old css files are in the /sass folder.

If you need to update any css file, you need to find the equivalent sass file and update it.

**Comment by mmilaprat** [comment]
I'm not sure if this issue still open because in my local environment these symbols appears when I add a concept or I load an existin model.

Probably the problem is that the first time that you enter in the form, the symbols don't appear.

**Comment by belalakbar** [comment]
@mmilaprat how can I update the sass file

**Comment by mmilaprat** [comment]
as a css file, you can add/update content in a scss file and if you have "compass watch" runnig the css is updated.

**Comment by YuriGlickman** [comment]
I still have the issue. See the sceenshots from Chrom and Mozilla
![symbols chrom](https://cloud.githubusercontent.com/assets/8254248/10216246/d8c9145a-6827-11e5-9d65-035bb6c3463f.jpg)
![symbols mozilla](https://cloud.githubusercontent.com/assets/8254248/10216245/d8c65936-6827-11e5-8d98-ad3c36ef4e42.jpg)

**Comment by mmilaprat** [comment]
you are right, I understand that you refer to the full bar

**Comment by mmilaprat** [comment]
We can solve this issue updating styles.

There is a PR pending that solve this issue https://github.com/policycompass/policycompass-frontend/pull/186
