### ISSUE TITLE
Add Concept, Edit Concept dialogues

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#246]
in the Add Concept, Edit Concept dialogues please:

1) add field "Value" as optional to allow users to set values manually. Most of users will use FCM editor without simulation.
2) Make field "description" optional

**Comment by aquinas9** [comment]
We will consider this issue again. 
However, as you remembered, our first design for Add Concept and Add Relationships had "value" field.
The reason we remove this field and move into the simulation section is that we tried to separate the simulation and model design. Set value can be considered as a part of simulation behaviour. 
But we will discuss this issue internally again.

**Comment by YuriGlickman** [comment]
Ok. I agree. Concept values are probably important only for simulation
