### ISSUE TITLE
"Run simulation" tab

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#247]
At the Run simulation tab please:

1) Deactivate buttons if clicking them does not do anything. For example, in the attached picture metrics are not added to concepts. So it is impossible to calculate weights from historical data. The corresponding button has to be deactivated until it becomes possible.  "Correlation matrix between concepts" does not work also, so deactivate the button.
2)When use clicks "Run simulation". You do not need to show a confirmation message. instead of that open the tab "Simulation results". 
3) When tab is openned its header should be in orange and stay in orange until other tab get selected.
4)Rename the button "Advance settings" to "Advanced Settings". Do the same with the "Advance settings" dialogue.

![run simulation](https://cloud.githubusercontent.com/assets/8254248/9839377/87a76d04-5a78-11e5-8690-2fccb320e1cd.jpg)

**Comment by YuriGlickman** [comment]
2)When use clicks "Run simulation". You do not need to show a confirmation message. instead of that open the tab "Simulation results". 
3) I cancel the request

Please do not close the issues if not all points are fixed.

**Comment by belalakbar** [comment]
@YuriGlickman regarding the domian size increase and auto selection of result tab. there are some limitation. i have spoke with @FabiApfelkern in last teleco he asked me to make new issue and assign him may b he can help. 
@YuriGlickman so can we close this issue?

**Comment by cbotsikas** [comment]
@belalakbar you can't close issues without resolving them; either by replying with detailed solution or linking to merged commits and/or new issues

**Comment by belalakbar** [comment]
@cbotsikas 
all the point of this issues are solved except the number 2, which I am facing some difficulty, where i need help from other partner. in last teleco I spoke with fabian he asked me make new issue and assign him so that is why I closed these issue and will make new issue to assign fabian and me.

**Comment by FabiApfelkern** [comment]
Left issue is now here: https://github.com/policycompass/policycompass/issues/356
