### ISSUE TITLE
Add dev server which is continously updated

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#25]
@FabiApfelkern tells @skous how to update DNS in order to reach dev server.

The server itself will be updated through CI, see #23.

**Comment by FabiApfelkern** [comment]
I have done this already and waiting for response.

**Comment by skous** [comment]
This issue was placed on hold as there were some discussions to transfer the domain, but as these were postponed I have forwarded this request now to our admin. 

--
Sotiris

**Comment by skous** [comment]
DNS entries updated!
