### ISSUE TITLE
"Graph" tab - visualisation of the simulation results

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#253]
In the dataset visualisation Miquel implemented a possibility to select a colour of curves. It would be good to have it also for simulation results

**Comment by mmilaprat** [comment]
Hi,
if you wish to set a color per each curve you need to add a new parameter into the dataset array used in the directive.

This is a dataset example:

[
{"Key":"France_1", "Labels":["2001","2002","2003"],"ValueX":["2001","2002","2003"], "ValueY":[744,662,702], "Color":"#a91d5b", "Type":"metric"},
{"Key":"Spain_0", "Labels":["1996","1997","1998"],"ValueX":["1996","1997","1998"], "ValueY":[65705,78846,81599], "Color":"#1f77b4", "Type":"metric"},
{"Key":"Germany_1", "Labels":["1996","1997","1998"],"ValueX":["1996","1997","1998"], "ValueY":[187022,205099,216682], "Color":"#aec7e8", "Type":"metric"}
]

**Comment by belalakbar** [comment]
@mmilaprat how can I use the color picker for each concept? As user can change the color on runtime. However, I understand the color attribute which you have describe in the dataset example is fixed.

**Comment by mmilaprat** [comment]
you can add a color picker field using a directive like this

<spectrum
name='color' 
ng-model="scaleColor" 
ng-model-onblur 
ng-change="your_function()"
options="{showInput: true, showAlpha: false, allowEmpty: false, preferredFormat: 'hex'}">
</spectrum>

your_function must be a function that update the appropiate ccolor row into your dataset.

**Comment by belalakbar** [comment]
@aquinas9 i spoke with younseok, it suggested that as each concept has already different color in graph so no need to changing color.

**Comment by cbotsikas** [comment]
@belalakbar i think you wanted to mention @YuriGlickman
