### ISSUE TITLE
Saving dialogue (cont. #153)

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#254]
1) Spelling mistake in the pop-up window name: "Causal" an not "Casual" :)
2) The size of the window with domains is still too small. At least 4 domains should be visible without scrolling.

![casual](https://cloud.githubusercontent.com/assets/8254248/9920965/08bbae3e-5cd9-11e5-8d31-cf9c35ebd35d.jpg)

**Comment by belalakbar** [comment]
@YuriGlickman regarding the domian size increase and auto selection of result tab. there are some limitation. i have spoke with @FabiApfelkern in last teleco he asked me to make new issue and assign him may b he can help. 
@YuriGlickman so can we close this issue?

**Comment by cbotsikas** [comment]
@belalakbar you can't close issues without resolving them; either by replying with detailed solution or linking to merged commits and/or new issues

**Comment by belalakbar** [comment]
@cbotsikas 
I have resolved the "Spelling mistake in the pop-up window name: "Causal" an not "Casual" :)" and its merged. but with second part, I need some help from team. I asked fabian he said to make new issue and assign it to him and me. 

normally what issue under new branch is merged I close that issue same as other.

**Comment by nadiapo** [comment]
All FCM dialogs have very big font in comparison to the rest of the portal. Please use same font sizes

**Comment by belalakbar** [comment]
@nadiapo 

We use the same css classes as other used.
For example,
'<div class="modal-header"><h4 class="modal-title">Simulation job has submitted successfully.</h4></div><div class="modal-footer"><button type="button" class="btn btn-default" ng-click="cancel()">Close</button></div>

How Can we change the font size for this?

**Comment by mmilaprat** [comment]
probalby if you delete class "input-group-lg" from the div the fields will be displayed better:

< div class="form-group input-group-lg"  ....

< div class="form-group"  ....

**Comment by cbotsikas** [comment]
Resolved
