### ISSUE TITLE
Error into the Metric detail page

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#255]
When I try to access to the metric detail page in my local environment I get an error.

url: http://localhost:9000/app/#!/metrics/2

error: {"detail":"Method 'GET' not allowed."}

In the console appears this message:
GET http://localhost:9000/api/v1/metricsmanager/metrics?id=2 405 (Method Not Allowed)

this url is not correct "metrics?id=2" must be "metrics/2"

After some research I think that the problem is because we have two 'Metric' definitions, one in the metricService.js and other into the fcmService.js

.factory('Metric', .....

In the stage server the error appears:
https://frontend-stage.policycompass.eu/app/#!/metrics/4

Into the alpha no:
https://alpha.policycompass.eu/app/#!/metrics/1

I know that both modules, metrics and FCM, are under construction, but it is possible to solve this bug? I have problems to check some functionalities.

@FabiApfelkern , @almey  , @belalakbar

**Comment by FabiApfelkern** [comment]
What functionality do you check with Metrics?

**Comment by mmilaprat** [comment]
I just check pages to find layout differences, it's rellated with the issue #200

**Comment by FabiApfelkern** [comment]
Ok, but the Metrics page is not relevant for that.

**Comment by slomo** [comment]
I can't reproduce this issue on [staging](http://frontend-stage.policycompass.eu/app/#!/metrics/4). Given this an its age it is probably outdated.
