### ISSUE TITLE
Cross-site HTTP requests using remote services

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#256]
When I configure my local environment to use remote services (useRemoteServices=true) I get an error.

XMLHttpRequest cannot load https://search-dev.policycompass.eu/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access.

How I can solve this problem?

**Comment by FabiApfelkern** [comment]
It is https://search-stage.policycompass.eu/
