### ISSUE TITLE
Setup PCompass in full production environment

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#26]
- [ ] ~~PostgreSQL for Django (migrate existing data on alpha)~~ (postponed for now)
- [x] Replace django dev server with gunicorn / waitress 
- [x] Maybe replace node.js with nginx for static deployment
- [x] FCM module needs CORS headers

**Comment by FabiApfelkern** [comment]
FCM CORS already done: https://github.com/policycompass/policycompass-fcmmanager/pull/3

**Comment by FabiApfelkern** [comment]
@nidico I think we should have this for the Review.

**Comment by nidico** [comment]
I agree. At least as much as possible.

**Comment by slomo** [comment]
Replaced with new issues #572
