### ISSUE TITLE
Logout after Refresh

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#260]
On my local machine I get logged out after a complete refresh of the page. Tested in Chrome.

**Comment by nidico** [comment]
Something seems to got broken. I'll check.

See also #259 and #216.

**Comment by nidico** [comment]
This should be fixed after liqd/adhocracy3.mercator#1727, could you please check again?

**Comment by FabiApfelkern** [comment]
@nidico  Unfortunately the error remains.

**Comment by slomo** [comment]
Is this still an issue?

**Comment by FabiApfelkern** [comment]
I have never tried it again. I'm only working with remote A3. Maybe I try some day but until then we can close this.
