### ISSUE TITLE
Use of Auth Service in Frontend broken

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#261]
I included  pcApp.auth.services.auth into a module and injected Auth into a controller to get the current logged-in user. This leads to a loggout of the user, when using that controller. Am I not supposed to use that service?

**Comment by nidico** [comment]
Yes, you're supposed to use that service. Marking as bug.

**Comment by nidico** [comment]
@FabiApfelkern - does this problem still persists? We're using the auth module without problems in other places...

**Comment by FabiApfelkern** [comment]
Seems to work.
