### ISSUE TITLE
Layout detail and form

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#264]
In reference to the issue #200 we propose to update general items layouts following the next rules (in the pull request # 162 there is the first version (just for visualisation and events)):

* the detail page: 
   * Buttons (edit, delete, ... ): must be placed in th top, under item title
   * Main data (title and description) will appear out of the "Details" section.
   * Details data will appear in a table with a specific class

* form page:
   * Header text: will be updated like the images attached (with icon item and help section)
   * Buttons: will (save, .. ) must be placed in th top, under item title

The next screenshots are the events and the visualisation layouts:

Event detail:

![event_detail](https://cloud.githubusercontent.com/assets/6602727/10044042/d18019c2-61f7-11e5-949c-551055dc80d5.png)

Event form:

![event_form](https://cloud.githubusercontent.com/assets/6602727/10043939/0baaf05a-61f7-11e5-90db-46f9399a917a.png)

Visualisation detail:

![visualisation_detail](https://cloud.githubusercontent.com/assets/6602727/10044022/9c3d3812-61f7-11e5-93e8-ba47902d5f6c.png)

Visualisation detail:

![visualisation_form](https://cloud.githubusercontent.com/assets/6602727/10043953/2088ed1a-61f7-11e5-9f5b-d15ca4446276.png)

**Comment by FabiApfelkern** [comment]
I checked it in the PR in detail and I would say this needs some improvement. The major issues is, like Yuri mentioned, there are too much empty spaces. Especially in the event page. Literally half the page is empty. And one other point. Is it possible to improve the small help button with the question mark? In my opinion it is too boring and know body will click on it. It needs a color perhaps....

**Comment by FabiApfelkern** [comment]
One other thing: In Visualization the graph menu (Legend, Lines...) is visible, even when there is no graph. It would be better to hide it. Moreover it would be great to have an info text what to do when there is no graph.

**Comment by bullz** [comment]
New event detail layout proposal
![event_detail](https://cloud.githubusercontent.com/assets/160349/10304223/1ff489a0-6c19-11e5-9d82-25bb24c44822.png)

**Comment by bullz** [comment]
![browse](https://cloud.githubusercontent.com/assets/160349/10309890/52623aa6-6c3f-11e5-89ef-2043519f3519.png)

**Comment by mmilaprat** [comment]
done!!
