### ISSUE TITLE
Link Policy Compass small logo reload entire page

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#267]
The small Policy Compass logo that appears on the top left, links to the home page but it reloads the entire page. Is this correct? or the link '<a href="#!"' must be replaced by '<a href="#!/"' ?

![top](https://cloud.githubusercontent.com/assets/6602727/10052317/8eaa04c6-6226-11e5-9818-be361b77e2f5.png)

**Comment by FabiApfelkern** [comment]
No it's not correct. You can change it.

**Comment by mmilaprat** [comment]
updated in the PR 223
