### ISSUE TITLE
I can read "terms an conditions" the link don't work

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#295]
When I try to register, the link "terms and conditions" don't work.

![14-10-2015 16-42-41](https://cloud.githubusercontent.com/assets/6602727/10487113/b64bb23c-7292-11e5-92ae-08fdbf64ee33.png)

**Comment by cbotsikas** [comment]
This is duplicate to https://github.com/policycompass/policycompass/issues/232
