### ISSUE TITLE
Help div cannot be hidden

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#296]
Although the initial idea was to use only the help icon/div at the top, depending how you use the help div in other parts when you click over it you cannot hide the div because it appears over the icon.

![14-10-2015 16-50-39](https://cloud.githubusercontent.com/assets/6602727/10487423/29a6c464-7294-11e5-8aae-38563f46a3ad.png)

**Comment by cbotsikas** [comment]
I think the same issue applies to visualization like you can see here: https://frontend-stage.policycompass.eu/app/#!/visualizations/create/

I think the help popup should have a close button on the top right corner.
You can also close it when clicking outside of it (add a semitransparent/blur fullpage overly under the help div) OR make it draggable if you think it's a good idea to keep it open while interacting with the ui.

**Comment by cbotsikas** [comment]
I also think that inside the help div, buttons should not change color and cursor on hover and not be clickable. At the moment, IMO, they look like broken... 
![capture](https://cloud.githubusercontent.com/assets/1640100/10487853/4b1c5d00-7296-11e5-915a-2f27a3c76250.PNG)

**Comment by cbotsikas** [comment]
for the blur part, you can see an example here: http://codepen.io/KristinB/pen/KFEIc 
If you don't like it, the traditional semitransparent colored overlay is fine too.

**Comment by mmilaprat** [comment]
PR # 214 ( policycompass/policycompass-frontend/pull/214)
