### ISSUE TITLE
Convert units of metrics if needed

### ISSUE THREAD

**Issue by slomo** [policycompass/policycompass#298]
If a two data sets of the same indicator are added or substracted in a formula it might be required to change their units to a common value before hand.

**Comment by FabiApfelkern** [comment]
This is planned for the Dataset Manager: https://github.com/policycompass/policycompass/issues/53
My plan is to have a parameter to change the unit of the values, when possible. I want to use the pint library for that.

**Comment by FabiApfelkern** [comment]
Dublicate: https://github.com/policycompass/policycompass/issues/53
