### ISSUE TITLE
Automatically start services on production and staging servers

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#299]
On server restart, policycompass doesn't start automatically.

**Comment by nidico** [comment]
@FabiApfelkern - please decide whether to move it to sprint 7, sprint 8 or year 3.

**Comment by FabiApfelkern** [comment]
We can have it in Sprint 7. Shouldn't be hard, should it? Just tell me, what the best way is to start supervisor on system start. An init.d script?

**Comment by FabiApfelkern** [comment]
@nidico I still need some instructions here. Thanks.

**Comment by slomo** [comment]
Simplest solution is to use upstart (included in ubuntu 14.04). Add the content below to the `/etc/init/policycompass.conf`:

```
description "Supervisord of policycompass"
gid policycompass
uid policycompass
chdir /home/policycompass/policycompass
exec /usr/bin/supervisord -n -c etc/supervisord.conf
```

**Comment by FabiApfelkern** [comment]
@slomo The upstart script is not recognized like this. The job is unknown. I even restarted the server. Are you sure the script has to look like this?
And I think the command will not start Adhocracy, we always had to start this separately via supervisor.

**Comment by FabiApfelkern** [comment]
Done. The exact script is this:
```
description "Supervisord of PolicyCompass"
start on runlevel [2345]
setgid policycompass
setuid policycompass
chdir /home/policycompass/policycompass
exec /usr/bin/supervisord -n -c etc/supervisord.conf
post-start script
    sleep 10
    supervisorctl start adhocracy:*
end script
```
