### ISSUE TITLE
add auth to the detail/edit item forms

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#311]
Hi @nidico ,
I'm trying to use auth into the FE. 

I understand how to use it into the add item form, it will be something like this (I checked metrics modules):

$scope.user = Auth;

if(!$scope.user.state.loggedIn) 
{
	$location.path("/login")
}
else 
{
    .......
    our code
    .......
}

but I have a question about how to enable the edit and delete buttons in the item detail page.

In the controller of the detail.html I can add something like this:

$scope.user = Auth;
$scope.canEdit = false;
$scope.canDelete = false;
	
$scope.$watch('user.state.loggedIn', function(newVal, oldVal) {    

if(!$scope.user.state.loggedIn) 
{
//not logged, then can not edit or delete
}
else 
 {	
       if($scope.user.state.isAdmin)
	{
              //is admin, can edit and delete
	      $scope.canEdit = true;
	      $scope.canDelete = true;	
	}   
	else if ($scope.user.state.userData.name==$scope.my_item.user_id)
	{
                //if is the author, can edit and delete
		$scope.canEdit = true;
		$scope.canDelete = true;				
	} 		
}
});

and the question is, what we are going to storage in the database as user_id? the user name (in my case mique.mila)? some id? because the object $scope.user don't have any id. 

I checked metrics manager backend and I cannot found any user id into th metric model.

**Comment by FabiApfelkern** [comment]
I think you store the user id which is an url, e.g. https://adhocracy-frontend-stage.policycompass.eu/api/principals/users/0000005/. But Liqid should confirm this. As for the Buttons, in my opinion we should find a generic solution for that, instead of settings variables in every controller. @MagdaN Do you have an idea about it?

**Comment by MagdaN** [comment]
1) the frontend does not need to take care of saving the user - this should be done in the backend (as the user is automatically added to the request), @slomo  already implemented it in the metricsmanager. I think the userfield is a read-only field and he added a presave method (see here: https://github.com/policycompass/policycompass-services/pull/68/files) to 

2) maybe we could write a directive that could be used for showing or not showing buttons everywhere. I can take a look at this if you want.

**Comment by mmilaprat** [comment]
it will be useful, we also need to control if user can edit or delete an item into the "edit" mode of it. Users can edit manualy URLs to add edit (item/numer/edit) into the url.

**Comment by MagdaN** [comment]
for that I would need to know all possible buttons or I could just start with:
- edit
- delete

**Comment by mmilaprat** [comment]
in my case, edit an delete are enough

**Comment by mmilaprat** [comment]
about backend, into the metricsmanager model there is the field creator_path where user information is stored (self.request.user.resource_path).

creator_path = models.CharField(max_length=1024, validators=[ RegexValidator("^(/[^/]*)+/?$") ])

creator_path is the "new" user_id field? we must update all models to harmonize APIs?

**Comment by MagdaN** [comment]
yes, you need to do that, @slomo also updated the migrations files (https://github.com/policycompass/policycompass-services/tree/master/apps/metricsmanager/migrations). I think, he first changed the user_id from integer to char field and in the next migration he changed the name.

**Comment by mmilaprat** [comment]
Ok, I'll rename the field user_id into the visualisation model.

**Comment by nidico** [comment]
@mmilaprat - do you still have an open question?

**Comment by mmilaprat** [comment]
I update visualisation model in order to arminize the field where we store tue user id.

**Comment by mmilaprat** [comment]
@MagdaN , do you know when the directive to know if user can edit/delete an item will be ready?

**Comment by MagdaN** [comment]
I am working on it just now

**Comment by mmilaprat** [comment]
thanks

**Comment by MagdaN** [comment]
I added a pull request for the directive: https://github.com/policycompass/policycompass-frontend/pull/220

please check if it works
