### ISSUE TITLE
Error creating a metric

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#314]
When I try to save a metric I get an error in the javascript console.

POST https://services-stage.policycompass.eu/api/v1/metricsmanager/metrics 400 (BAD REQUEST)

**Comment by slomo** [comment]
Can't reproduce this without more details. I can create a metric.

**Comment by mmilaprat** [comment]
Step 1

**Comment by slomo** [comment]
You for get to set the indicator and the frontend seems not to notice this. @MagdaN could you maybe have a look why it still allows to send the form?

**Comment by MagdaN** [comment]
yes
