### ISSUE TITLE
No Axis Label When Unitless

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#315]
When visualizing data without specific unit (unitless), the axis is labeled with "Unitless". It is better do not have this label in this case, just ave no label on the axis.

**Comment by mmilaprat** [comment]
Can you give me an example?

**Comment by FabiApfelkern** [comment]
In this screenshot it is "People". Just leave this label when it is Unitless. I didn't find a Unitless Example.

![screenshot from 2015-10-26 10-26-41](https://cloud.githubusercontent.com/assets/1488424/10725396/14bbbaa0-7bcc-11e5-92da-473e9835ad7a.png)

**Comment by mmilaprat** [comment]
I'm not sure, but probalby there is a unit called "Unitless" in the database. When a dataset doesn't have a valid unit (unit_id=0) the label is "No unit"


https://frontend-stage.policycompass.eu/app/#!/visualizations/create/?datasets=16

**Comment by FabiApfelkern** [comment]
This is not bug, I know there is a unit called Unitless. :) We just want the feature, that this unit is not displayed.

**Comment by mmilaprat** [comment]
ok, now I understand :-)

**Comment by mmilaprat** [comment]
Done. PR 210
policycompass/policycompass-frontend/pull/210
