### ISSUE TITLE
Better Action When Clicking on Legend Item

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#316]
When clicking on a legend item, the event modal opens. It would be much better to get into the edit menu of the dataset in order to change the color very quickly. At the moment the user has to navigate a lot to change the color. 

![screenshot from 2015-10-26 10-33-16](https://cloud.githubusercontent.com/assets/1488424/10725541/fe5b77ae-7bcc-11e5-9403-e83949775793.png)

**Comment by mmilaprat** [comment]
to do something like that, we must move the current way to open the event selector modal window.

To open the modal event window users should click over the lines, not over the chart area like now. It's correct for you?

**Comment by mmilaprat** [comment]
A posibility, if there are datasets related with a visualisation, when a user clicks over the button "Link Dataset" the modal window will opened with the tab "Datasets Configuration" actived by default.

We also can delete buton "Edit mode".

![26-10-2015 17-12-09](https://cloud.githubusercontent.com/assets/6602727/10734897/c45bacde-7c05-11e5-8a95-6c231dabe789.png)

**Comment by YuriGlickman** [comment]
Personally, I agree with Miquel's proposal. I would additionally:
1) rename the button "Link Datasets" to "Configure Datasets"
2) rename the tab "Search Datasets" to "Add Datasets"

**Comment by mmilaprat** [comment]
PR # 219 ( policycompass/policycompass-frontend/pull/219)
