### ISSUE TITLE
New unit categories

### ISSUE THREAD

**Issue by nadiapo** [policycompass/policycompass#320]
Please add the following unit categories:
- Percentage
- General unit

**Comment by FabiApfelkern** [comment]
Unit Category or Unit? Because Percentage is a Unit and already there. https://services-prod.policycompass.eu/api/v1/references/units/23

**Comment by nadiapo** [comment]
Unit Category as appears in the Define New Indicator screen
https://alpha.policycompass.eu/app/#!/indicators/create

**Comment by FabiApfelkern** [comment]
Ok. But Percentage or General Unit are not Unit Categories. A Unit Categorie is the physical dimension if an unit, like mass or length. Indicators are linked to a unit category, because it doesnt matter if you measure something in g or kg.

**Comment by nadiapo** [comment]
It is because I couldn´t find matching unit categories for those:
https://alpha.policycompass.eu/app/#!/indicators/10
https://alpha.policycompass.eu/app/#!/indicators/18

**Comment by FabiApfelkern** [comment]
What do you think might be the Unit for datasets linked to those indicators?

**Comment by nadiapo** [comment]
For one dataset is what I would propose a general type of unit (more specifically arms) and the other one is % GDP growth

**Comment by FabiApfelkern** [comment]
Ok. I think we cannot support such special units. Arms is unitless and for % GDP growth I would take just % and the rest is meta data. So both of your indicators are dimensionless.

**Comment by FabiApfelkern** [comment]
@nadiapo Can we close this for now?

**Comment by nadiapo** [comment]
Ok but units as they are now are not very helpful. We should rethink in the third year
