### ISSUE TITLE
Edit Indicator fails to preselect values

### ISSUE THREAD

**Issue by nadiapo** [policycompass/policycompass#325]
When I select to edit an indicator, sometimes it does not preselect the values for the Unit Category and Policy Domains fields. This does not happen always, usually when I go to edit for the first time in the same browser cache.

**Comment by FabiApfelkern** [comment]
@nadiapo This should be fixed on all servers now. Can you please check it?

**Comment by nadiapo** [comment]
How can I edit an indicator?

**Comment by FabiApfelkern** [comment]
You can only edit your own indicators. So just create a new one.

**Comment by nadiapo** [comment]
It was an indicator I created. do I have to create a new one anyway?

**Comment by FabiApfelkern** [comment]
For the moment. We haven't set the right users to the old ones yet.

**Comment by nadiapo** [comment]
It looks fine
