### ISSUE TITLE
Static Carneades Deployment

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#33]
The current version of Carneades in Policy Compass will not be development any further. Until we get the new version (based on a totally new stack) we should remove the Carneades build process from the make file (it is buggy anyway). Instead we should provide an already compiled war-file. I put this file on the alpha server under /home/policycompass/backup.  We should integrate it into this repo and deploy it during the make process.

**Comment by slomo** [comment]
I'd rather fix the build process than committing a 36 megabyte zip file to the repository.

**Comment by FabiApfelkern** [comment]
Ok, I understand your point.
