### ISSUE TITLE
Auth for FCM

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#330]
Auth needs also integration into FCM. So especially the backend needs to be prepared for it. 
@belalakbar @aquinas9 Are you working on this?

**Comment by FabiApfelkern** [comment]
@belalakbar @aquinas9 Please give some feedback here....

**Comment by belalakbar** [comment]
I will start working on this issue in next week.

**Comment by belalakbar** [comment]
Hi @FabiApfelkern 

Can you please elaborate this in detail?

**Comment by FabiApfelkern** [comment]
@belalakbar I talked with Yuri and we decided, that Auth for FCM is not that relevant for the review and to complex at the moment to implement. But please make this a priority after the review. Get familiar with our Auth API: https://github.com/policycompass/policycompass/wiki/Auth-Service. You need to integrate it into both backend and frontend.

**Comment by belalakbar** [comment]
@FabiApfelkern have you applied the Auth in metric manger can you give me path so I can have a look. 
or anyone else did so can you please give me a clue.

**Comment by FabiApfelkern** [comment]
The first step is: You have to implement a connection to our Auth-Service (https://github.com/policycompass/policycompass/wiki/Auth-Service )in your backend. We did this for our Python backend. You can see here (https://github.com/policycompass/policycompass-services/blob/master/policycompass_services/auth.py#L85) how we communicate with the Auth-Service. This may be a complex task, so you should start immediately. 
Second step is: Add the Auth check in the frontend, we cann discuss this after you have done step 1. :)
