### ISSUE TITLE
Upload Dataset wizard

### ISSUE THREAD

**Issue by nadiapo** [policycompass/policycompass#332]
- last step of wizard, external resource is mandatory but does not appear with an asterisk - worldbank and oecd is not there - shall we add it?
- if in step5 select to add a new indicator and then click cancel, I am redirected at the home page
- Step 7, cannot select language with keyboard, I always have to click on it with the mouse

**Comment by FabiApfelkern** [comment]
Moved issues to https://github.com/policycompass/policycompass/issues/338
