### ISSUE TITLE
Upload Dataset wizard

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#338]
* Why is it asking for an acronym? Does if have any meaning?
* Why is it mandatory to relate with an indicator? Uploading datasets should be independent from indicators!
* External Resource custom values not populated in list (e.g. World Bank). Shouldn't the list get populated by the user's input too?
* Dataset URL might be irrelevant when data not publicly available prior upload! Users should be allowed to upload private/not publicly available datasets (even if a “not trusted source” flag should accompany the dataset). In this case URL field is not applicable. 
* Dataset Dimension second resolution should be invisible or user definable (e.g. Age Group)
* When uploading from an excel file the platform only grabs the first sheet?

**Comment by FabiApfelkern** [comment]
Why is it asking for an acronym? Does if have any meaning?

 - This is part of our data model. It is used e.g. for metrics formulas.

Why is it mandatory to relate with an indicator? Uploading datasets should be independent from indicators!

- Each dataset HAS to be linked to an indicator. This is our methodology. 

External Resource custom values not populated in list (e.g. World Bank). Shouldn't the list get populated by the user's input too?

- This is an still ongoing discussion, how to handle user input for such namespaces. We should discuss in after the review. 

Dataset URL might be irrelevant when data not publicly available prior upload! Users should be allowed to upload private/not publicly available datasets (even if a “not trusted source” flag should accompany the dataset). In this case URL field is not applicable.

- Thats true.

    Dataset Dimension second resolution should be invisible or user definable (e.g. Age Group)

- Invisible? User definable is the same discussion as above

    When uploading from an excel file the platform only grabs the first sheet?

- Yes

**Comment by FabiApfelkern** [comment]
I include @nadiapo feedback here (https://github.com/policycompass/policycompass/issues/332): 

- last step of wizard, external resource is mandatory but does not appear with an asterisk - worldbank and oecd is not there - shall we add it?
- if in step5 select to add a new indicator and then click cancel, I am redirected at the home page
- Step 7, cannot select language with keyboard, I always have to click on it with the mouse

**Comment by takiant** [comment]
@FabiApfelkern 
Why is it mandatory to relate with an indicator? Uploading datasets should be independent from indicators!
- Each dataset HAS to be linked to an indicator. This is our methodology.

To get it right, only the selected/created indicator is stored in the platform, and not the complete dataset. Is that correct?
