### ISSUE TITLE
Language select box should be updated with the language selector used in Datasets

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#339]

**Comment by YuriGlickman** [comment]
Please provide more details.

**Comment by cbotsikas** [comment]
Indicators have an outdated UI and it's not aligned with the new design.
Specifically for this issue, the language selection is using the standard HTML Select box. 
![capture2](https://cloud.githubusercontent.com/assets/1640100/10920743/1cfb8a9a-8272-11e5-9e1b-79b4c34b3012.PNG)
Datasets, on the other hand, use the new PC select box.
![capture](https://cloud.githubusercontent.com/assets/1640100/10920745/2097837a-8272-11e5-93f2-ebda57ada5d7.PNG)

**Comment by mmilaprat** [comment]
Events and Visualisations also have the outdated UI.

**Comment by FabiApfelkern** [comment]
It is updated in all modules now.
