### ISSUE TITLE
Trying to visualise a dataset as a guest user, prompts to login

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#340]
Is this expected?

**Comment by YuriGlickman** [comment]
yes, we have ti fix that. Please re.assign

**Comment by mmilaprat** [comment]
Yes, it is because if you try to visulise a dataset you are redirect to the visualisation form, and only logged user can create content.

**Comment by FabiApfelkern** [comment]
Yes, only logged in users can create content, but when you only create it when you click on the "Save" button.

**Comment by mmilaprat** [comment]
then, guest user must be able to "play" with visualisation and only "Save" button must be "hidden"?

**Comment by FabiApfelkern** [comment]
As discussed today, deactivate the Save button until when user is not logged in.

**Comment by mmilaprat** [comment]
After the last PR guest users can access to the visualisation form
