### ISSUE TITLE
The search for indicators returns only the first 10 that were put in the platform.

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#342]

**Comment by YuriGlickman** [comment]
is it not your issue Christos ;)

**Comment by cbotsikas** [comment]
metrics doesn't use the search api but directly the indicators service. In either case, it's not supporting the pagination feature of the results.

**Comment by YuriGlickman** [comment]
So, Fabian?

**Comment by FabiApfelkern** [comment]
@cbotsikas What is the issue here, I don't get it?

**Comment by cbotsikas** [comment]
https://frontend-stage.policycompass.eu/app/#!/metrics/create-1 has a list o indicators to add in the formula but it only displays and filters the first 10 indicators from the api. eg https://frontend-stage.policycompass.eu/app/#!/indicators/16 is not listed there since it's the 11th indicator in the system.

**Comment by FabiApfelkern** [comment]
Ok, but this is an issue for Liqd then, isn't it?

**Comment by cbotsikas** [comment]
So it's @nidico ?
