### ISSUE TITLE
FCM Relationship Weights should include number

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#343]
e.g. Weak Negative (-0.5)

**Comment by YuriGlickman** [comment]
I am not sure about that. Imho "weak negative" is enough- What "0,5" tells you if you know nothing about FCMs

**Comment by cbotsikas** [comment]
I think the point here is that the diagram uses numbers where the forms use text and there is no relation between them. This is why we proposed to include the values along with the text.

**Comment by YuriGlickman** [comment]
Probably it is good to have both

**Comment by belalakbar** [comment]
ok I will do put number there

**Comment by belalakbar** [comment]
https://github.com/policycompass/policycompass-frontend/pull/229
