### ISSUE TITLE
Editing a relationship in an FCM from diagram doesn't keep weight

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#345]

**Comment by belalakbar** [comment]
can you please explain a bit more.

**Comment by takiant** [comment]
Let's suppose you have designed an FCM and you note that a relationship has a wrong destination concept.
Trying to edit the relationship through double-clicking it causes the initial weight to disappear.
This shouldn't be the case.

**Comment by belalakbar** [comment]
is this happen before you save the model?
if the answer then it will be case, because the values are saved after the model is saved. 
if you change the direction of a saved model then it keep the values. 


however editing a new model need to saved before the values appear.

**Comment by belalakbar** [comment]
https://github.com/policycompass/policycompass/issues/359

**Comment by belalakbar** [comment]
policycompass/policycompass-frontend#234
