### ISSUE TITLE
Linking datasets to specific concepts

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#346]
what does it offer? where’s the value?

**Comment by belalakbar** [comment]
Linking to dataset will provide the input data for calculating the fuzzy value of concept and weight of association. currently we are working on this issue and finalizing the methodology.

**Comment by belalakbar** [comment]
reference to https://github.com/policycompass/policycompass/issues/181

**Comment by belalakbar** [comment]
policycompass/policycompass-frontend#232

**Comment by YuriGlickman** [comment]
Weight calculation does not work. Please do not close the tickets until you tested that the implemented functionality actualy works.

**Comment by YuriGlickman** [comment]
I close this ticket and re-open #181 instead of it. It describes the task better
