### ISSUE TITLE
Cancel Button in FCM Edit View

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#357]

**Comment by belalakbar** [comment]
@mmilaprat I implemented this in Create/Edit Causal Model, kindly make changes in CSS for Save As button as well for proper view.

**Comment by belalakbar** [comment]
https://github.com/policycompass/policycompass-frontend/pull/226

**Comment by mmilaprat** [comment]
@belalakbar , a css update is not needed to solve this, if you update the links as buttons inside the button-group div they will be displayed correctly:

chanche this:
< a type="button" class="btn btn-primary btn-concept" ng-click="addObj()">Add Concept< / a >
< a ng-if="isDisabled == true" type="button" class="btn btn-primary btn-association" ng-click="addEdge()" disabled>Create Relationship< / a >
< a ng-if="isDisabled == false" type="button" class="btn btn-primary btn-association" ng-click="addEdge()">Create Relationship< / a >
.....


for this:

< button type="submit"  class="btn btn-primary btn-concept" ng-click="addObj()">Add Concept< / button >
< button type="submit"  ng-if="isDisabled == true" type="button" class="btn btn-primary btn-association" ng-click="addEdge()" disabled>Create Relationship< / button >
< button type="submit"  ng-if="isDisabled == false" type="button" class="btn btn-primary btn-association" ng-click="addEdge()">Create Relationship< / button >
< button type="submit"  ng-if="mode == 'create' && isDisabled == true" type="button" class="btn btn-primary btn-save" ng-click="saveModel()" disabled>Save Model< / button >
< button type="submit"  ng-if="mode == 'edit' && isDisabled == true" type="button" class="btn btn-primary btn-save" ng-click="updateModel()" disabled>Save Model< / button >
< button type="submit"  ng-if="mode == 'create' && isDisabled == false" type="button" class="btn btn-primary btn-save" ng-click="saveModel()">Save Model< / button >
< button type="submit" ng-if="mode == 'edit' && isDisabled == false" type="button" class="btn btn-primary btn-save" ng-click="updateModel()">Save Model< / button >
< button type="submit"  ng-if="mode == 'create'" type="button" class="btn btn-primary btn-save" ng-click="saveModel()" disabled>Save As Model< / button >
< button type="submit"  ng-if="mode == 'edit'" type="button" class="btn btn-primary btn-save" ng-click="saveModel()">Save As Model< / button >
< button type="submit" data-intro="Cancel" data-position="top" class="btn btn-default btn-danger" ng-click="cancelModel()">Cancel< / button >
