### ISSUE TITLE
Map visualisations

### ISSUE THREAD

**Issue by nadiapo** [policycompass/policycompass#375]
- colours between countries are usually very similar and very black
- it is usually very slow, needs to be smoother when scrolling through years - maybe by preloading data for all years so scrolling can be seamless?

**Comment by cbotsikas** [comment]
@nadiapo About the color issue, is it still valid? @mmilaprat had implemented initial coloring for the scale.

**Comment by nadiapo** [comment]
I believe colouring is fixed, what needs to be done is to smooth transition through the time scroll

**Comment by cbotsikas** [comment]
Ok, i've tracked the issue with the smooth transition and from what i understand, [map directive](https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/common/directives/mapscharts.js#L106) destroys and creates the map again, every time the slider changes. This should not happen. @mmilaprat you need to use liflet's methods to clear/reset the displayed data instead.
