### ISSUE TITLE
Cancel Button in FCM should use absolute path

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#377]
FCM's cancel button in edit view makes use of [window's history](https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/fcm/controllers/cytoscape.js#L318-L323) instead of absolute location.
For example, if you navigate to https://alpha.policycompass.eu/app/#!/models/4/edit and then click cancel it's not guaranteed that you'll get to https://alpha.policycompass.eu/app/#!/models/4.

**Comment by belalakbar** [comment]
@cbotsikas I have implemented this functionality using the code used by the visualization team. 
@mmilaprat can you please tell me how the available code you developed can be changed to address the above issue.

**Comment by mmilaprat** [comment]
in visualisations, the cancel button execute "window.history.back();"

**Comment by FabiApfelkern** [comment]
I think the Cancel button should just link to the read view of the entity. Like here with indicators: https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/indicators/partials/create.html#L23
