### ISSUE TITLE
Code format

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#378]

**Comment by cbotsikas** [comment]
Reponing for other repos

**Comment by FabiApfelkern** [comment]
@cbotsikas In what stae are we here?

**Comment by cbotsikas** [comment]
@FabiApfelkern I've left this open for other repositories like the fcm and services... I guess services doesn't need it since you've added and aligned the code with flake8.
I have no idea about the fcm...

We could just close this and reuse it in future code maintenance again, if needed.
