### ISSUE TITLE
Create pre-commit hook which checks proper code formatting

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#380]
In order to keep up with the nice code formatting introduced in policycompass/policycompass-services#88, we want to create a pre-commit hook which checks (currently the python code) for proper formatting and code smells with:

    flake8 apps policycompass_services --ignore E501,F403 --exclude migrations

We could create the post-commit hook from the `Makefile` of this repository, however not everybody uses it.

Steps:

- [x] Install flake8 locally
- [x] Add info in README of the services repository on how to install the pre-commit hook
- [x] Add pre-commit hook through Makefile in this repository
- [ ] Check coding style in travis

**Comment by cbotsikas** [comment]
@nidico about the commit hook, we should run these tests on travis and manual commands. We can't have git client hooks distributed. We can have the same process in front-end with jslint/hint. I've recently discovered https://linthub.io/ but the travis solution is better IMO.
I was also thinking that we could use also https://codeclimate.com/ and https://saucelabs.com/ which are both free for Open Source projects like PolicyCompass.

**Comment by cbotsikas** [comment]
@nidico My main concern about these tools on PC, is if we are willing to really enforce them on all PRs from now on or we are going to accept all of them regardless the results of those tools.
For example, although i've reformatted frontend (semi-automatically; i had to manually check almost all files and align the format errors) and send out an email asking to respect the formatting and how the commit messages should be formatted (which, by the way, we can also automatically check), I'm willing to accept [this PR](https://github.com/policycompass/policycompass-frontend/pull/263) which clearly doesn't meet any standard. Should we just reject such PRs?

**Comment by nidico** [comment]
> We can't have git client hooks distributed.

We can't force everybody to install the post-commit hook, but we can add it to the README, communicate it in the telco and pre-install it for those who use the Makefile (e.g. me). This already helps to avoid broken commits beforehand, while travis etc. will only detect the broken links afterwards.

Still I agree travis should fail if our style guide isn't fulfilled.

> Should we just reject such PRs?

I would reject those where we have pre-commit hooks in place.

**Comment by FabiApfelkern** [comment]
I agree that we have to enforce it! And our rules are not very strict. It's a good trade-off. When we have Travis in place, everybody will see when a PR is not valid and can react.

**Comment by FabiApfelkern** [comment]
@nidico Will you implement this?

**Comment by nidico** [comment]
Yes.

**Comment by nidico** [comment]
I've created a separate issue #389 for checking the coding style in travis and will therefore close this issue.
