### ISSUE TITLE
Filtering get lost after switching to a % view

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#383]
Here is  a concrete example of the bug:
https://alpha.policycompass.eu/app/#!/visualizations/36
if I deactivate data for France by clicking on the corresponding legends and then switch to a % view then the deaactivation French datasets get lost and I haver to deactivate them again :(

**Comment by mmilaprat** [comment]
it's not a "bug". Are different functionalities that updates the chart. I'll try to merge then, but I need to think how to do it.

**Comment by mmilaprat** [comment]
solved in the PR # 264
