### ISSUE TITLE
Auth Service needs Promise Callback

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#388]
I copied this issue basically from here: https://github.com/policycompass/policycompass-frontend/pull/223

I discovered a big issue with our Auth Service in this PR. In some controller the state of the user is checked and saved in a variable, which used in the template to activate or deactivate the save button. But if you load the page, e.g. with a complete refresh, the call to the auth backend may be not complete yet. So the user state is unknown, but maybe he is logged in. But the variable is set to false. We do need a promise on the Auth service, to set such variable async. I had a quick look in the Auth service, but I didn't found an easy solution to include such a promise

**Comment by nidico** [comment]
You can simply bind `Auth.state` to the scope, as the (trivial) `UserState` controller does. The template will automatically update, as done in `app/header.html`.
