### ISSUE TITLE
Facet label in Firefox collide with counter

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#394]
![image](https://cloud.githubusercontent.com/assets/1640100/11695311/c754f49c-9eae-11e5-9db2-6c6673be7115.png)

The problem is related to the CSS specification and implementation of text-overflow. There are various bug reports since 2013 about this issue. Although, i think, the specification was aligned in 2014, it's not clear if and what each browser will implement.

Related links:
https://bugzilla.mozilla.org/show_bug.cgi?id=944200
https://bugzilla.mozilla.org/show_bug.cgi?id=864759
https://bugs.webkit.org/show_bug.cgi?id=115746
https://www.w3.org/wiki/CSS3-UI#Issue_32
https://drafts.csswg.org/css-ui/#text-overflow

**Comment by FabiApfelkern** [comment]
I think it is still very tight, how close the brackets are to the right border.

![screenshot from 2015-12-16 18-00-11](https://cloud.githubusercontent.com/assets/1488424/11847668/df4594ce-a41e-11e5-8751-d6189ee33a0d.png)
