### ISSUE TITLE
Datasets configuration is missing

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#396]
If I create a visualisation of a dataset (but do not save it yet)
https://alpha.policycompass.eu/app/#!/visualizations/create/?datasets=60  
and want to deactivate one of the sub-datasets or change its color then the indivindual color  configuration options are missing
![indivindualcolor](https://cloud.githubusercontent.com/assets/8254248/11872945/59f7992e-a4d8-11e5-8b74-368c35e332d8.jpg)

**Comment by mmilaprat** [comment]
I tested and it works fine.
Today I discovered another issue related with individuals (issue # 397) that appears when you try to create a visualisation using the "visualise" button of dataset but as this environment is not updated with the last version of code it doesn't appear.There is a PR that solve this issue.

About your issue, can you give me more information about the steps you do? I cannot reproduce it.

**Comment by YuriGlickman** [comment]
I cannot reproduce it today to... I was pressing the "Visualise" button in the dataset and after that I was trying to configure the datasets. Today it works properly. So I close the ticket for now until I reproduce the issue again

**Comment by FabiApfelkern** [comment]
This is definitely an issue and I can reproduce it most of the times. I guess it has something to do with the async load of the dataset data. @mmilaprat Can you check again?

**Comment by mmilaprat** [comment]
I'll try to reproduce it

**Comment by mmilaprat** [comment]
I will add a loading div until the list of individuals is loaded

![05-01-2016 9-10-27](https://cloud.githubusercontent.com/assets/6602727/12110442/7d76fa62-b38c-11e5-8148-3e08b00a7f4c.jpg)
