### ISSUE TITLE
Weights and values changes cannot be saved

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#401]
If I change a weight of a relation or a value of a concept than this change cannot be saved. The model cannot be overwritten even if it created by me.

**Comment by vanaraj-zenex5ive** [comment]
Hi aquinas9,
This task is relavent to "As we can see below, the weight in canvas can vary from the value below the canvas. If user edit the weight in the canvas, the changed value should be reflect to lower part and vice and versa." this right?
