### ISSUE TITLE
Carneades graph graphical design

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#406]
Hi Nadia,

we need ATOS help to define a better look of Carneades graphs. Below you can see a screenshot from our Carneades editor, which we are developing. Please ask your designer to re-draw the graph (or a part of it) below, so it looked better and more inline with other parts of the Policy Compass. The top menu can be ignored. We are interested only in graph design. Some boxes in the graph have to stay red or green, but may be in another hue. Other colours can be freely modified.

![carneades](https://cloud.githubusercontent.com/assets/8254248/12294248/0d8a2706-b9f9-11e5-9152-a259214bf71f.png)

**Comment by bullz** [comment]
New graph design
![carneades](https://cloud.githubusercontent.com/assets/160349/12745073/d4b202d8-c997-11e5-9982-22b61cbbe225.png)

**Comment by YuriGlickman** [comment]
Thank you. Any comments from Andreas and Tom?

**Comment by FabiApfelkern** [comment]
Personally I think it looks to oldschool. I would go with a more modern flat style.

**Comment by tfgordon** [comment]
I think it would bettte to ask the them for suggestions for improvements of the design that I already have in the Carneades server at http://carneades.fokus.fraunhofer.de.  Andreas should, I think, first adjust his design to match mine.  And then we could ask their designer for suggestions.  There are too many things "wrong" or at least incomplete in the current version of Andreas' argument editor to use it as a starting point for the designers.  For example:

- Statement nodes should be displayed in rectangles (without rounded corners), to distinguish them more clearly from argument nodes, which do have rounded corners.
- There should be an arrow from an argument nodes to its conclusion.
- The + and + signs in circles, showing points at which edges can be attached, should be shown only when editing the graph.
- The role names of premises, e.g. "major" or "minor" should be displayed on the edges of premises.
- The name of the argumentation scheme applied should be displayed in argument nodes, next to id of the node, as in "a1: expert opinion".  
- Very long texts in statement nodes need to be broken into lines.  But no more than 3 or 4 lines should be shown. There should be maximal width for the boxes.   If the full text cannot fit in the provided space, truncate the text and show an ellipsis ("...") at the end.  The full text should be displayed in the details panel, on the right, when the node is selected.

One more thing: I prefer the color scheme we currently use to these colors.
