### ISSUE TITLE
Rework Event Creation

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#411]
At the moment the manual creation of an event is the first option and the automatic import is somehow hidden. It should be the other way around and the results of the event search should look more appealing.

**Comment by cueneythizli** [comment]
Features:
1)  The automatic import should be the first option and the manual creation of an event the second option
2) In the "Search for an Event" page, the "Start-Range-of-Event" field and the "End-Range-of-Event" field should not be required anymore. 
3) The design of the "Search for an Event" page should look like the "Browse the Policy Compass Data" page, with filters for the start date and the end date
4) If the return/cancel button is pressed, the fields that already contained information, should not be empty again

**Comment by FabiApfelkern** [comment]
https://github.com/policycompass/policycompass-frontend/pull/311
