### ISSUE TITLE
Dataset displays differently in bar charts on different devices

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#427]
The table for the same dataset display differently (different ordering of districts) depending on if the user is using a desktop or a mobile device such as a tablet. Should this be in alphabetical order. See the screenshots attached.  
![2_android_tables](https://cloud.githubusercontent.com/assets/1488424/12506540/08410e10-c0f0-11e5-9f93-ddfb130f371f.jpg)
![1_pcfirefox_tables](https://cloud.githubusercontent.com/assets/1488424/12506544/0b3f9cc6-c0f0-11e5-9a40-5f268965e505.JPG)

**Comment by FabiApfelkern** [comment]
@mmilaprat Don't do it immediately, let's discuss first if it's needed

**Comment by mmilaprat** [comment]
ok

just to add that bars charts has been updated recently, in te new version data are group by time

![bar chart](https://cloud.githubusercontent.com/assets/6602727/12506695/20ed51fc-c0f1-11e5-8d0c-620c4382d90c.jpg)
