### ISSUE TITLE
Improve Dataset and Event Search Models

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#429]
The search is not very intuitive. We should improve here. Just some points. We should discuss the BEFORE implementing:

- CCC expects that the search can be triggered by hitting "enter"
- We should improve the sensibility. It is just working with full words. So you are switching between results and no results. @cbotsikas How is elastic configured?

**Comment by mmilaprat** [comment]
@cbotsikas can you give me some tips about how I can update the search to improve the sensibility of the search ? I use elastic search in the modal windows in visualisation to search datasets and events.
