### ISSUE TITLE
import events form

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#432]
into the import events form the select box allows you to select n items but in fact it only takes into account one. 

![import events](https://cloud.githubusercontent.com/assets/6602727/12509868/006be708-c106-11e5-99ff-822888ae8bb0.jpg)

Can it be updated? it will be better that users only choose one event.

Other question, this import form, can be appear in a modal window?

**Comment by FabiApfelkern** [comment]
Actually we are working on restructuring the event import.
https://github.com/policycompass/policycompass/issues/411
