### ISSUE TITLE
Redirect when Visualization does not exist

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#435]
When a user enters a non existing visualization an error pops up. It should redirect to the browse page:
e.g. https://alpha.policycompass.eu/app/#!/visualizations/45

**Comment by mmilaprat** [comment]
Ok, I'll check but this happpens in events, fcm, indicators and metrics

E.g:
https://alpha.policycompass.eu/app/#!/events/300
https://alpha.policycompass.eu/app/#!/models/160
https://alpha.policycompass.eu/app/#!/indicators/160
https://alpha.policycompass.eu/app/#!/metrics/40

**Comment by FabiApfelkern** [comment]
Yes, but this ticket is for you. :)

**Comment by mmilaprat** [comment]
:-)
yes, I know, it just to "share" this ticket to all.
