### ISSUE TITLE
Bug in browse

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#438]
I have found how to reproduce the browse error.

Select “Visualisation” in "Content Type" :

https://alpha.policycompass.eu/app/#!/browse?_type=visualization

Select “InternationaI Issues” and “Population and So…” in "Policy Domains"

https://alpha.policycompass.eu/app/#!/browse?_type=visualization&_policyDomains=13&_policyDomains=8

Select “United Kingdom” in Location

https://alpha.policycompass.eu/app/#!/browse?_type=visualization&_policyDomains=13&_policyDomains=8&_location=234

Unselect “Population and So…” in "Policy Domains

https://alpha.policycompass.eu/app/#!/browse?_type=visualization&_policyDomains=13&_location=234

The "bug" appears. The filters desappear and you cannot change your search.

![browse](https://cloud.githubusercontent.com/assets/6602727/12614771/479ea3f4-c502-11e5-92a7-5e681daa5879.jpg)

**Comment by cbotsikas** [comment]
This issue should be mitigated when https://github.com/policycompass/policycompass/issues/443 gets deployed.
This issue can only occur if facets are set in the url and there no results. In this case i guess there should be a "clear filters [(and/or) search string]" button to reset the parameters.
