### ISSUE TITLE
Argument graph error on selecting "Porsche" example

### ISSUE THREAD

**Issue by nyreescott** [policycompass/policycompass#442]
![error message on argument graph](https://cloud.githubusercontent.com/assets/670833/12647034/31b52378-c5cb-11e5-88d0-a539f405f495.jpg)

**Comment by th0br0** [comment]
@FabiApfelkern did you make sure that all bower dependencies are updated? Could you remove bower_dependencies on the server and reinstall? This is an lacking lodash/underscore method alias AFAIR.

**Comment by FabiApfelkern** [comment]
Ok. I can do that. But for the record. It is working for me.

**Comment by FabiApfelkern** [comment]
Done!
