### ISSUE TITLE
Argument Graph question

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#445]
As anonymous user you can "edit" the argument graph.

example in https://frontend-stage.policycompass.eu/app/#!/ags/1 

is correct?

![10-02-2016 14-27-59](https://cloud.githubusercontent.com/assets/6602727/12948598/606e5698-d003-11e5-8ae8-9096d9047aa0.jpg)

Also, there is some problems with the star rating

![10-02-2016 14-28-31](https://cloud.githubusercontent.com/assets/6602727/12948604/6697548e-d003-11e5-97c2-056218edb1e1.jpg)

**Comment by FabiApfelkern** [comment]
Argument Graph is only in a DRAFT version at the moment. A lot of features are missing.
