### ISSUE TITLE
Add "Policy-Domains" Selection to Create Event Page

### ISSUE THREAD

**Issue by cueneythizli** [policycompass/policycompass#447]
Add "Policy-Domains" Selection to Create-Event Page

**Comment by cueneythizli** [comment]
https://github.com/policycompass/policycompass-services/pull/108
https://github.com/policycompass/policycompass-frontend/pull/307

**Comment by FabiApfelkern** [comment]
https://github.com/policycompass/policycompass-frontend/pull/311
https://github.com/policycompass/policycompass-services/pull/108
