### ISSUE TITLE
Event Save Button not working for event from search

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#449]
When you add an event via the event search the Save button never works. I worked around it by always activating it: https://github.com/policycompass/policycompass-frontend/pull/311
But this needs to be fixed.

**Comment by cueneythizli** [comment]
I think the problem could be the start and event date, because I think we can only add events which started after 1900

**Comment by FabiApfelkern** [comment]
Please check it out next week.

**Comment by cbotsikas** [comment]
This is not a proper solution. I would remove the min/max dates restriction, expanding the range doesn't solve the issue.
The GESIS scrapper needs more work. Apparently the api you're using is not consistent on the date format (which also brakes the assumption that the year is always the first 4 characters used for the url) so the start event date format is not always correct and probably that's the validation issue. @FabiApfelkern did the problem occur on all events or some of them?

![image](https://cloud.githubusercontent.com/assets/1640100/13444329/deaaf310-e005-11e5-930d-27baf8e69266.png)

I would also try cleaning the event descriptions from wikipedia annotations and markup, but this task can be tricky. 
for example:
''text'' is italic formatted text
ampampndash is -
ampampTEXTampamp is useless annotation 
ampref TEXTampamp is useless annotation 
ref TEXT{{TEXT}} is useless annotation 
{{TEXT}} is useless annotation 

It also appears to have outdated data but we can't do anything about that. For example [here](http://www.vizgr.org/historical-events/search.php?begin_date=00010101&end_date=20991231&query=war) "donation of Altavilla" is stated to happen on 1198/07/14 but based on [wikipedia](https://en.wikipedia.org/wiki/1098) it happened on 1098/07/14

**Comment by FabiApfelkern** [comment]
@cueneythizli Please investigate further!
