### ISSUE TITLE
Event and Policy Domain Facet

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#451]
Events have now Policy Domains in their schema. How do we integrate it into the Browse page?

**Comment by cbotsikas** [comment]
I think the problem is related with the fact that the policy_domains field's type for events is string, instead of integer like the rest of the apis. You should fix this API inconstancy.

**Comment by FabiApfelkern** [comment]
@cueneythizli Can you check, please?

**Comment by cueneythizli** [comment]
I will :)
