### ISSUE TITLE
Improve UI linking datasets and events

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#453]
Revert button should be disabled
Rename "Configure Datasets" and "Link Datasets"
Previous Next Buttons confusing
Rename "Add Datasets"
Remove Create new dataset button and Create a new event button
Event Modal directly to configuration
Rephrase Popup texts
Name of "Link Events"
Display dataset name if just one dataset in visu
Refactor legend and legend for events

**Comment by cbotsikas** [comment]
@mmilaprat, I think the following needs attention before closing this issue:
- _Rename "Configure Datasets" and "Link Datasets"._ What's the resolution?
- _Rename "Add Datasets"._ What's the resolution?
- There is a typo in "View Dataset in **detaill**". I would rename that to "Open dataset details"
![image](https://cloud.githubusercontent.com/assets/1640100/13445705/15d0a120-e00e-11e5-899c-d1ebc5e39d0f.png)

**Comment by mmilaprat** [comment]
In the main window we update the label of the button "Configure Datasets" to "Link Datasets"

In the modal window we can rename:
"Add Datasets" as "Search" or "Search Datasets"
and "Configure Datasets" as "Configure"

"View Dataset in detaill" wull be updated as "Open dataset details"
