### ISSUE TITLE
FCM help text

### ISSUE THREAD

**Issue by mohammedbahja** [policycompass/policycompass#454]
- Better help texts, different places

- Help Pop Up confusing: The help text in the Help Pop should be simple, short and understandable for the users who don't know any clue about FCM.

- It would be nice to add simple tutorial ( short video example could helpful ).

- Unicode Problem

- Wording not consistent

-  Save As should renamed to create a copy. 

- FCM Details should be similar to the other component.

**Comment by mohammedbahja** [comment]
@aquinas9 do you want me to do this ?

**Comment by aquinas9** [comment]
@mohammedbahja 
No~ I will give you the revised text. Please give me one days!
