### ISSUE TITLE
Policy Domain Selection

### ISSUE THREAD

**Issue by mohammedbahja** [policycompass/policycompass#455]
The user should be able to choose multi policy domain: Currently the use can use Ctrl or Shift buttons to select multi domain. Showing check buttons would be easer.

**Comment by cbotsikas** [comment]
@mohammedbahja please use [referenceSelectionForm directive](https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/references/directives/forms.js#L231) instead. For example you can check visualisation's code [@L277-L280](https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/visualization/partials/create.html#L277-L280)

**Comment by mohammedbahja** [comment]
@cbotsikas I tried, however, it's not easy to dive through such a code 
https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/fcm/controllers/cytoscape.js#L1611

I finish the high priority issues and I'll get back to this later.

**Comment by cbotsikas** [comment]
I'll make your life easier removing these nonsense templates cache.(https://github.com/policycompass/policycompass/issues/506)

I've a filling though, that the policy domains field is just a mock up. i don't see how the selections are handled and saved.

**Comment by mohammedbahja** [comment]
@cbotsikas I have managed to do it, I'll push the code now

**Comment by cbotsikas** [comment]
getting rid of templatecache or the policydomain wiring?

**Comment by mohammedbahja** [comment]
I have added the following to the  (   $templateCache.put('/dialogs/savemodel.html ... ) 

<label class="control-label" for="policyDomain">Policy Domain : *</label><div id="policy_domains_data" class="reference-selection pc-reference-selection-full" resource="PolicyDomain" selection-mode="multiple" output="metric.policy_domains" input="metric.policy_domains">
e="multiple" output="metric.policy_domains" input="metric.policy_domains">

**Comment by mohammedbahja** [comment]
![1](https://cloud.githubusercontent.com/assets/16784021/13918483/9ffd658a-ef5f-11e5-8f0e-6eddbe7ce56b.png)

**Comment by cbotsikas** [comment]
ok, but still, i don't think it's going to work. I tried it too locally, but maybe i did something wrong.
Anyway i'm getting rid of those unmaintainable template. once you push the change i'll align and push #506
