### ISSUE TITLE
FCM editer and colures  

### ISSUE THREAD

**Issue by mohammedbahja** [policycompass/policycompass#456]
1.The colure of the relationship arrows should be change to:

-  RED when  the Weight value is (-) 

- GREEN when the Weight value is (+).

- Gray  when Weight value is not assigned yet.

2.Change pointer when scrolling in FCM

3.When the user press one click over a consipt node then pop up edit window should not appear however the nodes colures should change according to the relationship type ( arrow direction ). If the user wants to edit a node details he/she should press double click over the node. 

4.In the edit mode, the user should click double click over a node to update a concept

**Comment by FabiApfelkern** [comment]
@mohammedbahja Please don't close an issue until the PR is merged.

**Comment by medh15** [comment]
@FabiApfelkern Acknowledged!
