### ISSUE TITLE
Move project page to project.policycompass.eu

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#460]

**Comment by cbotsikas** [comment]
This should be done ASAP in order to notify all search engines in time for the move

**Comment by FabiApfelkern** [comment]
Close to be finished. You can access it already (https://project.policycompass.eu/), but the WordPress links have to be changed. @cbotsikas can you do this or tell me what the best way is?

**Comment by FabiApfelkern** [comment]
There are also some issued with SSL, but we are working on it.

**Comment by th0br0** [comment]
SSL issues fixed, links fixed.

**Comment by cbotsikas** [comment]
There are more steps needed in order to fully move to the project subdomain that requires content manipulation. there are still hardcoded links to policycompass.eu. Please don't remove the policycompass.eu configuration yet from nginx
