### ISSUE TITLE
Create sample screencast as guide for user

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#463]

**Comment by rukala** [comment]
Please link it to live platform and close this task

**Comment by cbotsikas** [comment]
https://www.youtube.com/watch?v=0SDNXhkojw4

**Comment by mmilaprat** [comment]
If you wish I can add a link "Policy Compass Promo Video" into the footer menu (next to the Imprint, Privacity Statement, Contact and  About link) ?

![15-06-2016 12-14-03](https://cloud.githubusercontent.com/assets/6602727/16076293/e3d002d2-32f2-11e6-9efe-294af9e4132f.jpg)

**Comment by takiant** [comment]
From the dissemination perspective, it would be fine!

**Comment by cbotsikas** [comment]
I think it would be great to embed it on the landing page

**Comment by mmilaprat** [comment]
ok, I'll add a new section at the bottom of the landing page with the title "Policy Compass Promotional Video" and the video embeded.

**Comment by cbotsikas** [comment]
All screencasts are available on our [Youtube channel](https://www.youtube.com/channel/UC6MOYv1fL8yrnzw2Cj7YbHw) and embeded in "[Learn](https://policycompass.eu/app/#!/learn)" section of the platform
