### ISSUE TITLE
Remove Acronym from all places, backend and frontend

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#464]

**Comment by FabiApfelkern** [comment]
@slomo @MagdaN @mmilaprat Can you check for further occurrences of acronyms in your code? I saw something in the frontend of metrics and visualisations.

**Comment by cbotsikas** [comment]
This should help you: https://github.com/policycompass/policycompass-frontend/search?utf8=%E2%9C%93&q=acronym

**Comment by cbotsikas** [comment]
I can also see that Normalizer from metrics manager is still using acronym on the backend. Is this ok?
https://github.com/policycompass/policycompass-services/blob/master/apps/metricsmanager/normalization.py
https://github.com/policycompass/policycompass-services/blob/master/apps/metricsmanager/serializers.py#L55

**Comment by FabiApfelkern** [comment]
@slomo @MagdaN @mmilaprat Can you give some feedback, so we can close this issue?

**Comment by mmilaprat** [comment]
visualisations don't use acronyms

**Comment by MagdaN** [comment]
see here: https://github.com/policycompass/policycompass-frontend/pull/359

**Comment by cbotsikas** [comment]
I can still find "acronym" at the following locations. Do we need those?
Datasets:
[datasetControllers.js @L990](https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/datasets/controllers/datasetControllers.js#L990)
[datasetControllers @L1141](https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/datasets/controllers/datasetControllers.js#L1141)
Metrics:
[metric-edit.html @L42](https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/metrics/partials/metric-edit.html#L42)
[create-metric-1.html @L70](https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/metrics/partials/create-metric-1.html#L70)
[functions-table.html @L10](https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/metrics/partials/functions-table.html#L10)
[functions-table.html @L20](https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/metrics/partials/functions-table.html#L20)
[normalization.py @L14](https://github.com/policycompass/policycompass-services/blob/master/apps/metricsmanager/normalization.py#L14)
[normalization.py @L28](https://github.com/policycompass/policycompass-services/blob/master/apps/metricsmanager/normalization.py#L28)
[serializers.py @L55](https://github.com/policycompass/policycompass-services/blob/master/apps/metricsmanager/serializers.py#L55)

**Comment by slomo** [comment]
In all those metrics locations it is still needed, because those talk about the normalization acronyms.
