### ISSUE TITLE
Editing of a Dataset is not always possible

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#470]

**Comment by cueneythizli** [comment]
There seems to be no problem for new created datasets. I can only edit my own datasets and when I'm not logged in, I can't edit any dataset.

Maybe this problem only exists for datasets, which had been created a longer time ago and didn't save the creator path.

**Comment by cueneythizli** [comment]
I checked it again and this problem doesn't exist for new created datasets.
