### ISSUE TITLE
Redesign Landing Page

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#478]

**Comment by FabiApfelkern** [comment]
@nadiapo I assigned this to you for now...

**Comment by FabiApfelkern** [comment]
My comments:

- The bullets on the right side are overlapping with the feedback button
- The Create, Browse and Request buttons should be incorporated into the steps and should have a mascot too
- The steps are supposed to be connected with arrow, like in the old How-it-Works page
- The peach orange is not nice, I would go with a stronger orange
- The background images are generic and not appealing
- The mascot images could be bigger
- Less text!
- Buttons could be more flashy  
- Unneeded space in the last row (Dig Deeper)

**Comment by FabiApfelkern** [comment]
Can we tweak the big buttons a little bit more? I now I'm picky. :) But in general we have a more flat design on Policy Compass and the buttons are a little bit overloaded with flashy "3D" effects. And this red is not uses anywhere else.

**Comment by cbotsikas** [comment]
New comments:
https://github.com/policycompass/policycompass/issues/532
https://github.com/policycompass/policycompass/issues/533
