### ISSUE TITLE
Integerate better help functionality

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#481]
- The user should be guided through each process by interactive help texts

**Comment by FabiApfelkern** [comment]
See http://usablica.github.io/intro.js/)

**Comment by FabiApfelkern** [comment]
@mmilaprat You checked this already?

**Comment by mmilaprat** [comment]
I did a test few weeks ago, if there is a hidden object with help intro.js has problems because the hidden div help doesn't appear.

I'll try to do some more tests.

**Comment by mmilaprat** [comment]
@FabiApfelkern , can you close this issue?
