### ISSUE TITLE
Plot events on bar charts

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#502]
just to clarify how a bar chart with events can be plotted.

In this image there is an example of a bar chart with some related events.

![16-03-2016 17-00-25](https://cloud.githubusercontent.com/assets/6602727/13819199/f716f6bc-eb98-11e5-8873-15eee55eca36.jpg)

Events will be plotted as cirlces using their start date to fix them in the chart.

In this example there are:

-  2 events in 2010

- 1 event in 2013

- and 2 events in 2014

Do you agree with this approach?

**Comment by cbotsikas** [comment]
I think it's a good start. The only thing i would change is to add some spacing below the events (also for the line charts)

**Comment by mmilaprat** [comment]
This image is an example of the new approach of how the events can be plotted ober a bar chart. Do you agree?

![bar_chart_with_event_as_line_2](https://cloud.githubusercontent.com/assets/6602727/13992257/aea4633c-f11b-11e5-888b-00302c6863c4.jpg)
