### ISSUE TITLE
indicator parameter might not be an array

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#504]
Code [@L631](https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/fcm/controllers/cytoscape.js#L631) expects that the $routeParams.indicator is an array which is not always true. In fact, in most visualisation examples, the indicator is just one, thus the variable is string.
The current code will iterate the characters of the string $routeParams.indicator. For example, at https://frontend-stage.policycompass.eu/app/#!/models/create?indicator=13 it will look for indicator "1" and "3" instead of "13".
Instead, we need something like:
```
if ($routeParams.indicator != null) {
  var indicators = (angular.isArray($routeParams.indicator)) ? $routeParams.indicator : [$routeParams.indicator];
  angular.forEach(indicators, function (indicator) {
    ...
  });
}
```

**Comment by mohammedbahja** [comment]
hmm, I think there is no logic apply, when i consider 13 as 1 and 3 then it will fail if 1213
it will consider it as 1,2,1 and 3. what do you think ?

**Comment by cbotsikas** [comment]
yes, that's what i'm saying.. the current implementation doesn't check if the parameter is actually an array, thus in case it's only one with more than one digit ("13, "1213") the forEach block is executed for each character and that's the bug.

**Comment by cbotsikas** [comment]
Here's an other example. 
When using one indicator with id 19, the current code will load indicator 1 and 9 instead of 19.
https://frontend-stage.policycompass.eu/app/#!/models/create?indicator=19
![image](https://cloud.githubusercontent.com/assets/1640100/13892140/a73e307e-ed55-11e5-9715-62adccc6bb4d.png)

**Comment by cbotsikas** [comment]
@mohammedbahja never mind, it's fixed.

**Comment by mohammedbahja** [comment]
@cbotsikas Many thanks, appreciate it!
