### ISSUE TITLE
Visualisation: Recomendation engine to link events

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#51]
Add a recomendation engine based on the visualisation data

**Comment by mmilaprat** [comment]
There is one, but as probably we must add more criterias we move it to sprint 4

**Comment by mmilaprat** [comment]
At this moment the recommendation engine shows the events that has been linked with other visualisations that uses the same datasets. To improve this engine we can try to show the events related with the country os the dataset.

@cbotsikas , @FabiApfelkern , @almey , can we search historical events (using the events manager or the search manager api ) by country?

**Comment by mmilaprat** [comment]
Does anyone ( @cbotsikas , @FabiApfelkern , @almey ) know how to find historical events by country?

**Comment by almey** [comment]
at the moment you can only search for an event by title and timeframe. a seach by country is not yet implemented.

**Comment by FabiApfelkern** [comment]
The only thing I know is that you can filter for any field by making a POST to https://search-prod.policycompass.eu/policycompass_search/event/_search with Payload
```
{"size":10,"from":0,"sort":["_score"],"query":{"match":{"geoLocation":"52.521332, 13.342037"}}}
```

The thing is that @almey does not use the Reference Poll for the Geo Location. But you can simply create new events and write the ID of country into the field GeoLocation,

**Comment by mmilaprat** [comment]
Probably is better that we move this issue until the functionality to search by country (1 or n) will be implemented.

Do you agree that we move it to sprint 5?

**Comment by FabiApfelkern** [comment]
You can do this, but as a I said it is availabe with Elastic Search. You should try it and suggest improvements for it by creating issues.

**Comment by mmilaprat** [comment]
close.
pul request related # 158
