### ISSUE TITLE
visualisation: new design for the configuration bar

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#511]
this is a proposal for the new design

![30-03-2016 10-57-36](https://cloud.githubusercontent.com/assets/6602727/14137125/b4a2f500-f666-11e5-9693-41abc3c1e9cd.jpg)

do you agree?

**Comment by mmilaprat** [comment]
is not difficult to add the list of events inside the bar configuration as is shown in the next image. Each event can be linked with their color selector. (This is only in "edit" view)

![30-03-2016 12-25-44](https://cloud.githubusercontent.com/assets/6602727/14139367/dca55302-f672-11e5-9cef-b8416b25c40b.jpg)

**Comment by th0br0** [comment]
The two columns on the left have got a fixed size whereas the number of events is dynamic. In my opinion, it'd make sense to split these two parts (e.g. by making the two left columns horizontal again, consuming half the area, and keeping the events in the right half of the screen.

On the other hand, the events are listed twice without reason. Why not remove the third (events) column and allow users to modify the event colour by clicking on the event name below the chart? 
That way, we'd save a significant amount of screen area.

**Comment by mmilaprat** [comment]
under the chart appears the list of events as legend (this legend appears in edit and in view mode), if you click over there the modal window that enble users to link/configure events is opened, then you can update colors, descriptions add or delete events.
