### ISSUE TITLE
FileEncoder is not working correctly for some EDP Datasets

### ISSUE THREAD

**Issue by cueneythizli** [policycompass/policycompass#512]
For example for a CSV file: 
"http://www.europeandataportal.eu/data/api/3/action/resource_show?id=bf99a951-a7d8-4159-97f4-7ebc271cbb7e",
"http://www.iwm.org.uk/upload/csv/Imperial-War-Museum-Spend-Transparency-2010-07.csv"

In datasetmanager/api.py line 83, the encoding from the CSV file failes.

**Comment by FabiApfelkern** [comment]
@cueneythizli Is this still an issue?

**Comment by cueneythizli** [comment]
No. It's solved
