### ISSUE TITLE
Standard Bootstrap Dropdown Menu is not working

### ISSUE THREAD

**Issue by cueneythizli** [policycompass/policycompass#518]
I tried to add a standard bootstrap dropdown menu like this: 

```html
<div class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" data-   toggle="dropdown">Dropdown Example
          <span class="caret"></span></button>
          <ul class="dropdown-menu">
            <li><a href="#">HTML</a></li>
            <li><a href="#">CSS</a></li>
            <li><a href="#">JavaScript</a></li>
          </ul>
        </div>
```

But when I click on the button, the dropdown menu is not expanding.

I tried out another example for a dropdown menu:

        <button class="btn" dropdown class="dropdown-toggle" dropdown-toggle>
                Dropdown
           <span class="caret"></span>
            <ul class="dropdown-menu">
                <li><a>Link 1</a></li>
                <li><a>Link 2</a></li>
            </ul>
       </button>

This solution is working fine in Chrome, but not in Firefox. The dropdown menu is expanding, but the elements are not clickable.

**Comment by FabiApfelkern** [comment]
@mmilaprat Can you forward this to your designer?

**Comment by mmilaprat** [comment]
where do you try to add these dopdown menus?

**Comment by cueneythizli** [comment]
First I tried it in the datasets/partials/step1.html .

After that, in the footer.html and header.html. But it was also not working there

**Comment by mmilaprat** [comment]
I'm going to check

**Comment by mmilaprat** [comment]
After some research I found that depending the versions of jquery, bootstrap the dropdown cannot work propertly.
https://github.com/angular-ui/bootstrap/issues/2998

I attach you some new ways to use this directives:

```html
    <div class="dropdown" dropdown>
		<button class="button btn btn-primary dropdown-toggle" dropdown-toggle>Dropdown Example <span class="caret"></span></button>
		<ul class="dropdown-menu">
			<li><a href="#">HTML</a></li>
            <li><a href="#">CSS</a></li>
            <li><a href="#">JavaScript</a></li>
		</ul>
	</div>
```


```html
	<div class="btn-group" dropdown >
		<button type="button" class="btn dropdown-toggle" dropdown-toggle >Dropdown <span class="caret"></span></button>       
        <ul class="dropdown-menu" role="menu">
            <li><a>Link 1</a></li>
            <li><a>Link 2</a></li>
        </ul>
	</div>
```

**Comment by cueneythizli** [comment]
It seems to be working!
Thank you!
