### ISSUE TITLE
Login/Signup

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#526]
In the Login form appears a link to the "Signup" form (or register "here"). If you access to the register form using this link, the "Signup" option of the top menu is not actived like if you access to this form using the top menu option. 

Also into the "Signup" web form appears the link "Cancel" that redirects you to a white page.

**Comment by slomo** [comment]
The cancel issue was removed in ddf22e8790e56222985600b96e889db9b259181e. The other issue is really hard to solve due to the login being in an embed. It has been proposed to move the login / signup into modal dialog, maybe we should change the issue to do this instead?

**Comment by cbotsikas** [comment]
one solution would be to watch the iframe's url but it's not efficient nor important. 
the modal dialog would be nice. Check the last meeting pad notes

**Comment by slomo** [comment]
Solved by implementing login in PC frontend
