### ISSUE TITLE
Multiple locations for datasets

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#529]
I think it is a know problem, but it seems to be not resolved. It should be possible to asociate one datsets with many countries.

**Comment by cueneythizli** [comment]
It's already possible to save multiple countries for one dataset. There is a new field named "spatials" and a new model "DatasetInSpatial" in the backend. It's also integrated in the frontend.

**Comment by YuriGlickman** [comment]
Ok. I just saw that it is impossible on alpha... On stage I did not try it.
