### ISSUE TITLE
New Landing Page

### ISSUE THREAD

**Issue by nyreescott** [policycompass/policycompass#532]
Using Google Chrome on a 17'' screen, Windows platform.  The landing page is quite "spread out", initially when you land on the new page there is no indication that there is anything under the "Browse, Create and Request  - .  There is excess white space above and below  the Policy Compass first "header" section which if reduced would at least give the user a better indication of something being available at the bottom of the screen?

**Comment by nyreescott** [comment]
text for Requests:  needs changing
currently it reads "Request non existent content..

Make a request from Data Experts for data that is for currently unavailable

**Comment by nyreescott** [comment]
Please before the platform goes live - it is  absolutely **essential **that someone goes in and clears out and deletes  the "old" requests that were put in by a user called "God"!!

**Comment by nyreescott** [comment]
Paragraph
:  
If the data is not already present in Policy Compass, it would need to be found elsewhere and uploaded to Policy Compass first. You may navigate to Create and then go to Upload Datasets in order to import the data tables into the Policy Compass system and define the indicator that this data represents

May I suggest:

If the Open Data source that you would like to use with Policy Compass has not already been uploaded, use this function to jump immediately into uploading Data Tables and also to define an indicator that represents your chosen data.

**Comment by mmilaprat** [comment]
About "the new page there is no indication that there is anything under the "Browse, Create and Request"

There are indicators on the right (see image attached) of the screen. We are going to update the border color (from grey to orange), then it will be more visilble.

![25-04-2016 8-48-48](https://cloud.githubusercontent.com/assets/6602727/14776217/597bb37e-0ac5-11e6-9431-8b259ac26d62.jpg)

**Comment by mmilaprat** [comment]
landing page updates has been done.

about content created by "God", I cannot delete it.

**Comment by nyreescott** [comment]
Who created it?

**Comment by mmilaprat** [comment]
do you refer to delete content of the user 'god' in stage?

Just to remember that the content of stage (https://frontend-stage.policycompass.eu/app/#!/ ) is only to test the platform.

**Comment by nyreescott** [comment]
This would not look good If this is visible for the public launch

**Comment by YuriGlickman** [comment]
We have to rename God in "Admin" or "Administrator"

**Comment by cbotsikas** [comment]
@YuriGlickman agreed, using "God" might be offensive
@nyreescott you are referring the content of stage platform which will not be published on public launch

**Comment by cbotsikas** [comment]
i've created https://github.com/policycompass/policycompass/issues/535 for the god rename issue
