### ISSUE TITLE
nginx old website redirect

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#548]
since the project website is located under https://project.policycompass.eu we need to permanently redirect all requests to the old location.
The platform will work with the following urls (when released for public launch):
https://policycompass.eu/ (redirects temporarily (302) to https://policycompass.eu/app/)
https://policycompass.eu/app/*
https://policycompass.eu/bower_components/*

The nginx redirection rule should check if the request is not following the above url patterns, and the redirect permanently (301) to https://project.policycompass.eu/$1 

For example if the request is:
https://www.policycompass.eu/news/
it should be redirected to 
https://project.policycompass.eu/news/

or 
this:
https://policycompass.eu/wp-content/uploads/2014/03/D2.2-Policy-Compass-Architecture-year2_v4.1.pdf
to:
https://project.policycompass.eu/wp-content/uploads/2014/03/D2.2-Policy-Compass-Architecture-year2_v4.1.pdf

**Comment by cbotsikas** [comment]
note that currently we use both www.policycompass.eu and policycompass.eu (without www subdomain). Both should be handled

**Comment by slomo** [comment]
Are you sure that you want to use 301. If you use 301 it can never be reliably undone, because those are cached indefinitely.

**Comment by FabiApfelkern** [comment]
https://github.com/policycompass/policycompass/pull/553

**Comment by cbotsikas** [comment]
Yes, it must be 301 in order to let search engines know about the change. Otherwise it's considered as a new site. The change is permanent either way, we moved permanently the website from policycompass.eu to project.policycompass.eu

---- Yves Müller wrote ----


Are you sure that you want to use 301. If you use 301 it can never be reliably undone, because those are cached indefinitely.

**Comment by FabiApfelkern** [comment]
@slomo @cbotsikas It is already working. But is everybody happy how it is now?

**Comment by cbotsikas** [comment]
ATM, the redirection is set to 302 which is temporarily. It should be 301 to indicate that the site has moved permanently. This tells Google and other search engines that the site has permanently moved and they will change the address from the results.

**Comment by slomo** [comment]
> The change is permanent eitheThe change is permanent either way, we moved permanently the website from policycompass.eu to project.policycompass.eu way, we moved permanently the website from policycompass.eu to project.policycompass.eu

But the semantic of 301 is a bit stronger than that. It says whatever is/was reachable here will alawys be reachable under the other domain in the future. Which will burn any currently valid path under `policycompass.eu/*` for future usage. Is that what we want? I understand your argument with the search engine, but I had issues with browser in the past which were very nasty and broke it even more.

**Comment by cbotsikas** [comment]
Yes, I'm 100% sure we need 301, since the WordPress website has moved permanently. Till we place the 301, Google will [report old url results](https://www.google.gr/search?q=site%3Apolicycompass.eu). You can read more about this at https://support.google.com/webmasters/answer/83106?hl=en

---- Yves Müller wrote ----


The change is permanent eitheThe change is permanent either way, we moved permanently the website from policycompass.eu to project.policycompass.eu way, we moved permanently the website from policycompass.eu to project.policycompass.eu

But the semantic of 301 is a bit stronger than that. It says whatever is/was reachable here will alawys be reachable under the other domain in the future. Which will burn any currently valid path under policycompass.eu/* for future usage. Is that what we want? I understand your argument with the search engine, but I had issues with browser in the past which were very nasty and broke it even more.

**Comment by FabiApfelkern** [comment]
@slomo What about this issue?
