### ISSUE TITLE
pagination in browse

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#550]
If I filter by "content type", 
https://frontend-stage.policycompass.eu/app/#!/browse?_type=event

then I click over pagination next, next,. ...
https://frontend-stage.policycompass.eu/app/#!/browse?_type=event&page=3

then I uncheck the "content type" filter
https://frontend-stage.policycompass.eu/app/#!/browse?page=3

the "page" parameter still in the url

now, If I select another "content type" we are redirect to the page 3 (or to the last page of contetn type if the maxim pagination is small than the current page parameter)
https://frontend-stage.policycompass.eu/app/#!/browse?_type=fuzzymap&page=3

**Comment by cbotsikas** [comment]
@mmilaprat What's the issue with this?

**Comment by mmilaprat** [comment]
When I update some filter like "content type", I expect that the pagination was set to 1

**Comment by mmilaprat** [comment]
the same, if after paginated results (go to page 3 of intial results) I search for a word using the filter and the buttom "Go" (word "test") the parameter page must be set to 1.
