### ISSUE TITLE
Impact analysis chart

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#555]
In the "Impact Analysis" modal window we plot a chart. 

I understand that the data ploted as table must be plotted as a chart.

In this causal model (https://frontend-stage.policycompass.eu/app/#!/models/74/edit)

the table to plot can be like this:

<table>
<tr><td>Initial Value of 1</td><td>0.2</td><td>0.4</td><td>0.6</td><td>0.8</td><td>1</td></tr>
<tr><td><b>1</b></td><td>0.2</td><td>0.4</td><td>0.6</td><td>0.8</td><td>1</td></tr>
<tr><td><b>2</b></td><td>0.54</td><td>0.57</td><td>0.61</td><td>0.65</td><td>0.68</td></tr>
</table>

As I understand the chart must plot 2 lines, one per the row "1" and other per the row "2" but the chart only plots on line because the directive receive a dataset like this:

[{"Key":"1","ValueX":["01","01","02","02","03","03","04","04","05","05"],"ValueY":[0.2,0.54,0.4,0.57,0.6,0.61,0.8,0.65,1,0.68],"Type":"FCM"}]

To plot 2 lines, the directive must receeive a dataset like (one row per line):

[{"Key":"1","ValueX":["01","02",,"03",,"04","05"],"ValueY":[0.2,0.4,0.6,0.8,1],"Type":"FCM"},{"Key":"2","ValueX":["01","02","03","04","05"],"ValueY":[0.54,0.57,0.61,0.65,0.68],"Type":"FCM"}]

**Comment by mohammedbahja** [comment]
@mmilaprat  many thanks. Ok, I will fix this. 

@aquinas9

**Comment by mmilaprat** [comment]
Hi,
I checked the datasets you send to the visualisations, if you wish to add a text label per each row inestead of a number like it apperas now into the impact analysys chart, you must add the label in the dataset like in this example:

$scope.dataset = [{"Key":"text legend_13883956","ValueX":["01","02","03","04","05"],"ValueY":[0.2,0.4,0.6,0.8,1],"Type":"FCM"},{"Key":"text legend2_13883957","ValueX":["01","02","03","04","05"],"ValueY":[0.54,0.57,0.61,0.65,0.68],"Type":"FCM"}]

The value of "Key" must be something like "label text" + "_" + "unique id per row". Wher "_" is used to split the "label" and the "unique id"

into the modules/common/directives/linecharts.js

there is an "example" of how to use each parameter.
