### ISSUE TITLE
Contact link in bottom menu

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#556]
The "contact" link that appears at the bottom menu doesn't work, there are different solutions:

we can redirect it to the contact page of the webs site ( https://project.policycompass.eu/contact/ ) 
or we can delete it because we have the "Feedback" functionality.
or we can open the same modal window that the "Feedback" link opens

what do you think?

**Comment by FabiApfelkern** [comment]
https://github.com/policycompass/policycompass-frontend/commit/08f4c1291d81ffb9c9df39d5999673c851c71b2f
