### ISSUE TITLE
error message on Causal model

### ISSUE THREAD

**Issue by nyreescott** [policycompass/policycompass#558]
using google Chrome
trying to exit the causal model without having created one
![image](https://cloud.githubusercontent.com/assets/670833/14916035/0a748d62-0e0f-11e6-995f-ee5b0cffe1b1.png)

**Comment by FabiApfelkern** [comment]
@mohammedbahja I can reproduce this error!

**Comment by cbotsikas** [comment]
resolution?

**Comment by mohammedbahja** [comment]
Duplicated issue 
policycompass/issues/574
