### ISSUE TITLE
Error Message on Alpha Causal Map

### ISSUE THREAD

**Issue by nyreescott** [policycompass/policycompass#559]
Error message When I am trying to put an impact analysis on the Causal Map 
![image](https://cloud.githubusercontent.com/assets/670833/14916236/336b87f6-0e10-11e6-87d9-96ba90316cfc.png)

**Comment by mmilaprat** [comment]
can you try to press F5 to reload the code? and try again. It seems to be and error with the chart that has been solved.
I tested and it works.

**Comment by FabiApfelkern** [comment]
@nyreescott Is this solved?
