### ISSUE TITLE
"Hertz" as a measure??

### ISSUE THREAD

**Issue by nyreescott** [policycompass/policycompass#563]
I have noticed that indicators are still requiring a unit measure of "Hertz" - surely this is wrong?  or we need at least time, frequency, measure?

![hertzpolicy compass](https://cloud.githubusercontent.com/assets/670833/14920404/434d5f68-0e25-11e6-9737-28f13f654717.jpg)

**Comment by th0br0** [comment]
Hertz is a completely valid unit. Hertz is an SI(!) unit defined as [1/s], i.e. once per second.

You can find further information here: https://en.wikipedia.org/wiki/Hertz

For example, when your monitor says it has 60Hz, that means that it's refreshing the image sixty times a second.

**Comment by th0br0** [comment]
You should be able to select a unit other than Hertz though

**Comment by FabiApfelkern** [comment]
This will be updated with this issue: https://github.com/policycompass/policycompass/issues/473
