### ISSUE TITLE
Import dataset problem

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#564]
If you try to import dataset following the next steps an error apears.

Import from External Resources = "European Data Portal"

Search = "Spain"

Select resource from "Local development plan of Spain epagnette" = any csv

An error appears into the browser console:

angular.js:8609 GET https://services-stage.policycompass.eu/api/v1/datasetmanager/ckan/download…l.eu%2Fdata%2Fapi%2F3&convert=true&id=ac5476a2-f82c-4740-b982-c194e081a338 500 (INTERNAL SERVER ERROR)

but as user you don't get any message and the page never ends to load.

![03-05-2016 10-28-04](https://cloud.githubusercontent.com/assets/6602727/14978117/e297249a-1119-11e6-8704-7785894facfe.jpg)

**Comment by cueneythizli** [comment]
I think that's not the latest version of the page on frontend-stage.policycompass.eu. 
When you try it on policycompass.eu you won't get this error and a popup will open with this message: "Selected dataset cannot be displayed. Please choose another one."

**Comment by mmilaprat** [comment]
You are right, in policycompass.eu appears the messages, and I update my local environment with the last version and it works.
