### ISSUE TITLE
Import html datasets

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#565]
It's posible to detect if a dataset is an html to avoid it?

Some times we get "html" code in the Grid 

Example:

Import from External Resources = "European Data Portal"

Search = "Italy"

Regional elections, in 2014. Preference votes — list: DEMO

![03-05-2016 11-02-55](https://cloud.githubusercontent.com/assets/6602727/14978807/b317332c-111e-11e6-9155-7ac5c08144f1.jpg)

**Comment by FabiApfelkern** [comment]
That is a general problem of Open Data portals. You have to rely on the mime type which is set within the meta data. This is sometimes wrong. We can solve this problem in the scope of Policy Compass.
