### ISSUE TITLE
FCM Delete function. 

### ISSUE THREAD

**Issue by mohammedbahja** [policycompass/policycompass#566]
The delete function on the server does not work.

**Comment by FabiApfelkern** [comment]
@mohammedbahja I can still not delete as admin.

**Comment by mohammedbahja** [comment]
@FabiApfelkern, I have tested this on the server as you can see from the images below. 
I have a normal username called brunel ( For testing purposes) . I have created new model as brunel. Then, I have used my username mbahja ( admin user ) to delete the same model. 


1- Normal user has created a model. 
<img width="1254" alt="5" src="https://cloud.githubusercontent.com/assets/16784021/15098184/26f3fe52-152e-11e6-9fe7-27c7f1ef3643.png">


2- Admin user is deleting the model
<img width="1244" alt="2" src="https://cloud.githubusercontent.com/assets/16784021/15098185/36c26530-152e-11e6-9a79-13fb78a13240.png">


3- Admin user has deleted the model.
<img width="1252" alt="3" src="https://cloud.githubusercontent.com/assets/16784021/15098188/43ba4f46-152e-11e6-923c-dc7689a05be3.png">

**Comment by FabiApfelkern** [comment]
Ok. But I got the issue. It is not working for models which have a userpath null. Like this: https://policycompass.eu/app/#!/models/42 But we have to be able to delete those too. We need to clean up. :)

**Comment by mohammedbahja** [comment]
@FabiApfelkern I thought that the userpath for the old records in my local DB was null, then I discovered that in my DB userpath null is not allowed!!. Why the on-line DB was accepting null values ?! There is a mismatch of datatype in db and java. 
Anyway the issue has been fixed and tested.
