### ISSUE TITLE
user image in "request"

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#568]
If we cannot upload an avatar to our user profile probably it will be better to delete the user avatar that appears in the request page. All avatars are the same.

![03-05-2016 14-59-47](https://cloud.githubusercontent.com/assets/6602727/14983843/e3049662-113f-11e6-90cd-394cbc72bc04.jpg)

Also, we only add the username in the detail page of other items (visualisations, events, datasets,...)

![03-05-2016 15-04-58](https://cloud.githubusercontent.com/assets/6602727/14983946/78b6cd2e-1140-11e6-8941-e317a61d93de.jpg)

**Comment by MagdaN** [comment]
Yes, showing the avatar can be switched off

**Comment by slomo** [comment]
Fixed on master and deployed to stage
