### ISSUE TITLE
Legends: sometimes the legend is a number instead of a string

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#573]
![11-05-2016 18-32-12](https://cloud.githubusercontent.com/assets/6602727/15188591/d2a60c3e-17a6-11e6-91ee-3ffc94d0ab14.jpg)

**Comment by cbotsikas** [comment]
I was able to reproduce the issue by blocking requests for individuals like https://services-prod.policycompass.eu/api/v1/references/individuals/363. The PR fixed the issue but i think you don't need to request the individuals any more. @mmilaprat is that true? maybe you should consider removing the requests
