### ISSUE TITLE
FCM Cancel Button in create mode

### ISSUE THREAD

**Issue by mohammedbahja** [policycompass/policycompass#574]
The cancel button redirects  the users to [https://policycompass.eu/app/#!/models/undefined](url)
instead of  [https://policycompass.eu/app/#!/browse](url)

**Comment by cbotsikas** [comment]
This issue was occurring only when the FCM was a new one (from Create menu). With the provided solution it's not working as intended for existing FCM (from Edit or Run Simulation buttons of an existing one). It should be something like:
````
            dlg.result.then(function () {
                if (id) {
                    $location.path('/models/' + id);
                } else {
                    $location.path('/browse');
                }
            });

**Comment by mohammedbahja** [comment]
Thanks @cbotsikas for this
