### ISSUE TITLE
User Management & Authentification

### ISSUE THREAD

**Issue by MagdaN** [policycompass/policycompass#585]
- User settings
- 
- Language Settings
- Password
- Avatar
- Emailadresse
- Registration & Password reset automatically based on front-end language
- User messaging
- Django Plugin to use A3 Authentication System

for the avatar, we could also use Gravatar

**Comment by slomo** [comment]
There are no translations so language settings can not be done.

**Comment by slomo** [comment]
Deplyed with new A3 version
