### ISSUE TITLE
Error in impact analysis when concepts are looping

### ISSUE THREAD

**Issue by mohammedbahja** [policycompass/policycompass#609]
The impact analysis is not working for single loops. 
<img width="789" alt="1" src="https://cloud.githubusercontent.com/assets/16784021/16567628/c2a47216-4218-11e6-86bb-999a45545fec.png">

**Comment by mohammedbahja** [comment]
@aquinas9 could you please give an example of this ? I tested it and it works but please double check for me.

**Comment by YuriGlickman** [comment]
Here is an example:
https://policycompass.eu/app/#!/models/20/edit

**Comment by mohammedbahja** [comment]
@YuriGlickman many thanks for this. I run the impact analysis for the example and it works. Could you please let me know what exactly does not work. 
<img width="1010" alt="1" src="https://cloud.githubusercontent.com/assets/16784021/17253251/ca416464-55a7-11e6-9cc5-d22910a7a3c4.png">

**Comment by aquinas9** [comment]
Hmm, I also failed to reproduce the error from the model..

-------- Original message --------

**Comment by YuriGlickman** [comment]
you are right. This one works.
