### ISSUE TITLE
Change the name and position of Metric column 

### ISSUE THREAD

**Issue by mohammedbahja** [policycompass/policycompass#611]
<img width="1103" alt="1" src="https://cloud.githubusercontent.com/assets/16784021/16567982/9bf1a680-421c-11e6-9baa-0df66ac6f25c.png">

**Comment by cbotsikas** [comment]
Not resolved yet

**Comment by mohammedbahja** [comment]
Seems that I did not commit the html file. I will check this 
<img width="518" alt="1" src="https://cloud.githubusercontent.com/assets/16784021/16796712/fce0917a-48db-11e6-9590-db230e48ec4b.png">

**Comment by mohammedbahja** [comment]
Done!
<img width="1116" alt="1" src="https://cloud.githubusercontent.com/assets/16784021/16869035/c2b2e992-4a72-11e6-9232-071919c90d21.png">
