### ISSUE TITLE
Add "draft" property to all entities

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#618]

**Comment by mmilaprat** [comment]
to unify all the entities, how we must call this new field into the backend? draft? possible values: "true" and "false"? or "1" and "0"?

**Comment by cbotsikas** [comment]
I'd say "is_draft" with boolean values, so:
```
is_draft = models.BooleanField(blank=False, default=False)

**Comment by slomo** [comment]
What is the semantic of this value? I suppose draft resources should only be visible to their author/creator? Or is it only to display it on the resource? 

Should they also appear in listings? In that case we should probably also add fields to the listings.

**Comment by cbotsikas** [comment]
Yes, the value is indicating if the resource is visible only to the author or not. 
If by listings you refer to the REST API, then yes we need it there too, not only on the models.

**Comment by slomo** [comment]
And how is it handed in ES? If I remember correctly we don't have authentication on the Elastic Search. So we also have to filter that the drafts won't be added to search in the signal handlers.

**Comment by cbotsikas** [comment]
We discussed about it during the last meeting. We will index them and filter the results on frontend. We can't do much since ES is exposed. The aim of draft is not to secure the entities, rather to ensure that others don't use it by accident while the author is still working on them.

**Comment by mmilaprat** [comment]
to harmonize, how we must add this new field to our forms into the FE? we must add a new checkbox with the label "draft"? or a radio button with two options (publish,draft)?
what do you think?

**Comment by mmilaprat** [comment]
another idea to add the checkbox into the FE is to use something like this http://www.bootstraptoggle.com/

**Comment by YuriGlickman** [comment]
Miquel,
for new (not saved) visualisations the status has to be draft by default. Please make the switch position "Public" in blue instead of gray to show that it is active. The same blue as of the active chart type button.

**Comment by mmilaprat** [comment]
"draft" functionality has been updated with PR policycompass/policycompass-frontend/pull/481

**Comment by slomo** [comment]
What is the state here?

**Comment by mmilaprat** [comment]
Visualisations has draft property
