### ISSUE TITLE
Fixed List of Licences

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#619]

**Comment by FabiApfelkern** [comment]
- Add new Reference Pool Entity with the following licences: http://licenses.opendefinition.org/licenses/groups/all.json
- Fixtures
- Django Command for getting the licences
- Frontend Integration
- Migrationskonzept

**Comment by cueneythizli** [comment]
https://github.com/policycompass/policycompass-services/pull/140
https://github.com/policycompass/policycompass-services/pull/141
https://github.com/policycompass/policycompass-frontend/pull/488
