### ISSUE TITLE
UI design for new metrics manager front ends

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#62]

**Comment by nadiapo** [comment]
we will provide an html proposal for the metrics manager wizard

**Comment by nadiapo** [comment]
will upload on github tomorrow. screenshots attached
![capturas policy](https://cloud.githubusercontent.com/assets/4747814/8697698/76094d02-2af7-11e5-8dca-876e1ad64fa1.png)
![capturas policy-2](https://cloud.githubusercontent.com/assets/4747814/8697701/796dec96-2af7-11e5-8dde-ca97719b78a0.png)
![capturas policy-3](https://cloud.githubusercontent.com/assets/4747814/8697706/7f19d9fc-2af7-11e5-8143-81a909fc878a.png)

**Comment by cbotsikas** [comment]
Merged https://github.com/policycompass/policycompass-frontend/pull/123
