### ISSUE TITLE
Unified Save/Cancel Buttons

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#620]

**Comment by mmilaprat** [comment]
can you give me more information about this issue?

**Comment by mmilaprat** [comment]
@FabiApfelkern, I must update all webforms to unify buttons or everyone must do their own form?

the proposal to unify save/cancel buttons is the next image

![05-09-2016 10-48-47](https://cloud.githubusercontent.com/assets/6602727/18242426/90df7fb8-7356-11e6-818c-3613dd8ec300.jpg)

**Comment by mmilaprat** [comment]
the responsible for each functionality should review its buttons

**Comment by mmilaprat** [comment]
if a user edits an item that belongs to another user the label of the button "save" must be "Save a copy"

**Comment by slomo** [comment]
I implemented this now for metrics manager, and to me it seems it was the last service not supporting this.  Therefore I am closing this now!
