### ISSUE TITLE
visualisation hanging

### ISSUE THREAD

**Issue by nyreescott** [policycompass/policycompass#628]
![image](https://cloud.githubusercontent.com/assets/670833/16682032/32f5a6fa-44f0-11e6-8e6c-4ca5e8488052.png)  
error message :  {"detail":"Not found"}

when the Visualisation of "ESA Claiments in Cambrigeshire 2011-2015" is attempted - site seems to hang and no visualisation occurs.  It then does not allow user to get back to previous screen - constant circle going around

**Comment by cbotsikas** [comment]
The affected URL: https://policycompass.eu/app/#!/visualizations/72
It appears that the dataset used in this visualisation doesn't exist.
@nyreescott, what do you mean with "it doesn't allow user to go back"? if you get rid of the 3 error pop-ups, you can still navigate and use PolicyCompass normally. 
Of course the 3 pop-ups is not normal nor explain the issue, but i'll address this in a new ticket.
