### ISSUE TITLE
Dataset manager responds with 500 when dataset doesn't exist

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#629]
for example https://services-prod.policycompass.eu/api/v1/datasetmanager/datasets/192 results to a 500 error response instead of a 404 not found.

This is related to https://github.com/policycompass/policycompass/issues/628

**Comment by mmilaprat** [comment]
the problem is that a dataset linked with a visualisation has been deleted.

**Comment by cbotsikas** [comment]
@mmilaprat i guess you wanted to respond to #630
