### ISSUE TITLE
Visualisation error handling

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#630]
we need better error reporting when the dataset doesn't exist.
If i can guess based on the fact that there are 3 pop-ups, visualisation asks for the same dataset details 3 times which i don't see the point.

For the dataset existence, you need [proper server response](https://github.com/policycompass/policycompass/issues/629)

related issue: https://github.com/policycompass/policycompass/issues/628

**Comment by mmilaprat** [comment]
the error appears becasuse a dataset has been deleted, how a dataset can be deleted? in this momnet it is not possible, no?
