### ISSUE TITLE
top events legends

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#636]
if there are overlap events they must appear in diferent lines

![13-07-2016 11-48-17](https://cloud.githubusercontent.com/assets/6602727/16799177/c1c5c7f4-48ef-11e6-9c42-a1f0c53c8723.jpg)

**Comment by cbotsikas** [comment]
As discussed, the automated process can be as simple as the following:

For each event, check if you can plot it on the each existing raw without overlapping existing events.
If it overlaps, add a new raw and add the event there.
Else, add the event it that raw and move on.
