### ISSUE TITLE
FCM stage server issues 

### ISSUE THREAD

**Issue by mohammedbahja** [policycompass/policycompass#640]
I get this when I try to open any FCM. 

Example 
https://frontend-stage.policycompass.eu/app/#!/models/35/edit

<img width="957" alt="1" src="https://cloud.githubusercontent.com/assets/16784021/16948345/096acd28-4dac-11e6-82c7-a4a5fde2ffab.png">

**Comment by mohammedbahja** [comment]
@cbotsikas what changes have done on staging? Could you please have a look on this.

**Comment by cbotsikas** [comment]
@mohammedbahja not sure what's wrong and i can't really check stage server. The build log looks ok to me. You can have a look [here](https://travis-ci.org/policycompass/policycompass-services/builds/145868935). Stage server is running the latest master.
Maybe @slomo can help. The [fcm-stage server](https://fcm-stage.policycompass.eu/) is just replying with 404, regardless the url

**Comment by cbotsikas** [comment]
The FCM related deployment log can be seen after line [315](https://travis-ci.org/policycompass/policycompass-services/builds/145868935#L315)
