### ISSUE TITLE
Separate keywords with commas

### ISSUE THREAD

**Issue by mohammedbahja** [policycompass/policycompass#641]
1- How are we going to separate keywords with commas? Are we going to ask the user to type "," between each keyword ? Any ideas ? 

<img width="1166" alt="1" src="https://cloud.githubusercontent.com/assets/16784021/16985836/f84bc9b4-4e7a-11e6-974c-cf386b3e3627.png">

2- As long I am going to include concepts names of the FCM to display related models ( using Elasticsearch ) how this service would be reusable by other components?

**Comment by mohammedbahja** [comment]
@YuriGlickman @cbotsikas @FabiApfelkern @aquinas9 Looking forward to hearing from you soon.

**Comment by mohammedbahja** [comment]
<img width="854" alt="1" src="https://cloud.githubusercontent.com/assets/16784021/16986536/f158a858-4e7e-11e6-8697-3885717c559f.png">
I am implementing functionality that will return keyword == 'cat' or =='cat,mat' or ='mat,cat'

**Comment by mmilaprat** [comment]
about keywords in the FE. Can be something like this?
In the webform users view a text field called keyword, this is a text field and all the data that a user writes in this field is a "keyword", if the user wishes to add another keyword, another text field will apear in the form. At the end we will have an array of keywords strings.

**Comment by mohammedbahja** [comment]
policycompass/policycompass/issues/610
