### ISSUE TITLE
Cannot save a causal model with a second one hop loop.

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#642]
I am the owner of this model:
https://policycompass.eu/app/#!/models/104/edit 

I can press "Save Model" a get a positive confirmation.

However, if I add a relation "Housing need" -> "Empty homes" (+0.75) and press "Save Model" then I get an error message "To run the simulation, please save the model". The error may be is caused by a single hop loop, which I created by a new relations. From another side the model contains another one hop loop already...

Please have a look. Anyway it is a wrong behavior.

**Comment by mohammedbahja** [comment]
This has been fixed in this [PR](https://github.com/policycompass/policycompass-frontend/pull/477).
