### ISSUE TITLE
Combining of datasets of different time resolution

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#643]
If I have a dataset with time resolution"month" https://policycompass.eu/app/#!/datasets/221  I cannot add in its visualisation a dataset with time resolution "year" https://policycompass.eu/app/#!/datasets/220 . In opposite order it is possible.

But if I add an Event "UK Financial crisis" https://policycompass.eu/app/#!/events/90 to the resulting visualisation, then the whole application crash.

**Comment by mmilaprat** [comment]
About first issue.
You can only plot datasets in their resolution or higher one (if it's month it can be plotted in moths oo in years)

If you wish to plot a chart using the 2 datasets in the order you mention, you need to select the dataset that has resolution of month, link it to the dataset, then change the resolution into the "resolution" combo that appears under the chart and lastly link the other dataset.

the resolution combo is loaded by default in the same resolution that the 1rst dataset has. In this case resolution is month, due that after link a dataset with a month resolution  you can only link datasets that their resolution is day or month if you don't change the combo.

About the second issue, I can create a visualisation with theses datasets and the event, can you attache a screenshot of the crash?

**Comment by YuriGlickman** [comment]
for the first issue, it should be possible change the resolution of a datasets automatically if I am adding it to a visualisation with lower resolution...
Otherwise, user does not understand why it is not possible to add a dataset to a visialisation.
I will add a screenshot for the second issue in a minute

**Comment by YuriGlickman** [comment]
![bug](https://cloud.githubusercontent.com/assets/8254248/17103358/3e9969f6-527e-11e6-8ac7-d31929234d94.jpg)

**Comment by mmilaprat** [comment]
About the first issue, it's not a simple task, if there is time I'll try to find a solution.

I'm working to solve the second issue.

**Comment by mmilaprat** [comment]
about first issue (mix datasets)

I can add an advice into the modal window like these screenshoots.

When a dataset cannot be linked due to the granularity a question mark will appear

![29-07-2016 13-42-47](https://cloud.githubusercontent.com/assets/6602727/17247304/af5cc86a-5592-11e6-89a4-9d96e34cff64.jpg)

If users click over the question mark the explantion will appear.


![29-07-2016 13-43-03](https://cloud.githubusercontent.com/assets/6602727/17247343/d8b247f8-5592-11e6-88aa-12811f4d0433.jpg)


do yo agree?

**Comment by YuriGlickman** [comment]
What I do not understand why you cannot change the resolution automatically.
If you recognise that the user adds a dataset with a lower resolution you can change the resolution automatically to a lower one, or? Basically you need to compare the reolution attributes of datasets and apply the lowest one to the visualisation. I do not understand the issue...

**Comment by mmilaprat** [comment]
when we have more than one dataset linked, the logic to find a valid resolution for all become difficult.

**Comment by YuriGlickman** [comment]
you just take the lowest...

**Comment by mmilaprat** [comment]
add this logic in the modal window needs a lot of changes

**Comment by mmilaprat** [comment]
after the PR policycompass/policycompass-frontend/pull/481 users can combine datasets with different granularities easier
