### ISSUE TITLE
Rename tab "Search" to "Select Datasets" 

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#644]
In the pop-up window "Edit Datasets" Rename tab "Search" to "Select Datasets" 
![edit datasets](https://cloud.githubusercontent.com/assets/8254248/17099860/4d4ade0c-526b-11e6-8a17-9d17fcebc3f5.jpg)

**Comment by mmilaprat** [comment]
done

**Comment by mmilaprat** [comment]
For events, tab "Search" must be renamed as "Select Events"? and the modal window title "Link an event" must be replaced by "Edit events"?

**Comment by YuriGlickman** [comment]
Yes, I think it is better.

**Comment by mmilaprat** [comment]
done in PR policycompass/policycompass-frontend/pull/481
