### ISSUE TITLE
Concepts names

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#646]
In many FCMs the text box for concept names is too small. That makes the whole FCM looking ugly. In some case the concept name is printed outside of the box like here:
https://policycompass.eu/app/#!/models/109

I strongly recommend to increase the height of the concept boxes on 50% and allow priting  of text in two lines. That should solve the most of the problems.

**Comment by mohammedbahja** [comment]
Hmm, interesting I think this happens when you type the concepts name in a block letters.  I will fix this.
