### ISSUE TITLE
IDs instead of dimensions

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#647]
Still we have an issue with dysplaing the dimension names. Instead of that we see IDs like on the screenshot below for this visualisation https://policycompass.eu/app/#!/visualizations/66
Please fix this bug asap.
![dimensionsbug](https://cloud.githubusercontent.com/assets/8254248/17139746/009cefc4-5346-11e6-9427-dee24a7d15b6.jpg)

**Comment by mmilaprat** [comment]
can you confirm me if you were using the last version of PC when you got this error? 

Yesterday the alpha version has been updated but if you had opened an old version in a browser probably you need to push F5 before test it.

**Comment by mmilaprat** [comment]
@YuriGlickman can we close this issue? the latest updates solves this issue, but can you confirm that this issue disappears?
