### ISSUE TITLE
Save FCM from visualization

### ISSUE THREAD

**Issue by mohammedbahja** [policycompass/policycompass#648]
When a user create an FCM from visualization, it could not be saved.

**Comment by YuriGlickman** [comment]
It can be saved if you have 2 nodes...

**Comment by mohammedbahja** [comment]
@YuriGlickman it does not. I am working on this. 
<img width="1030" alt="1" src="https://cloud.githubusercontent.com/assets/16784021/17209930/a975c87e-54b7-11e6-908e-ece9d2e3f82a.png">

**Comment by YuriGlickman** [comment]
There are 2 other bugs related with saving from Visualisation. Maybe it is related with the old bug.
1) after saving another copy of the concept, which was added from visualisation gets added.
2) if I press "Save" again I get an error message. See the screenshot. The second concept node "Economic deprivation" was added when I pressed "Save Model":


![Uploading fcmbug2.png…]()

**Comment by YuriGlickman** [comment]
![Uploading fcmbug.jpg…]()

**Comment by YuriGlickman** [comment]
![fcmbug](https://cloud.githubusercontent.com/assets/8254248/17963268/fe21ef16-6ab4-11e6-8564-b9333ed92648.jpg)

**Comment by mohammedbahja** [comment]
- Backend (java application) is not working on the production server. Please see the link below. @slomo cloule you please help in this ? 
https://fcm-prod.policycompass.eu/api/v1/fcmmanager/models

- However, it works over the stage 
https://fcm-stage.policycompass.eu/api/v1/fcmmanager/models


- I am checking the saving issue.

**Comment by YuriGlickman** [comment]
On the prod server the certificate has to include the subdomains. We are working to fix the issue

**Comment by mohammedbahja** [comment]
@YuriGlickman after deep investigation on this weird issue, I would say it's a deployment problem on the stage server. Please see my points below. 

1- The saving issue is not exist on the prod server. I know the "Create FCM model " button is disabled now however you can use this link and verify it. 
https://policycompass.eu/app/#!/models/create?indicator=22

2- I have installed the latest version of code from the policycompass/policycompass-fcmmanager and I deployed the code over another new local machine and it works well. Please see the recored video in the link below. 
https://www.dropbox.com/s/g7i2osdyjg7ypv3/2016-08-25_1724.swf?dl=0

3- I think the problem could be the same as policycompass/policycompass-fcmmanager/pull/40

Thanks 
Mohammed

**Comment by YuriGlickman** [comment]
thank you @mohammedbahja . On th main server it works now. Before it was not working. Indeed it seems to be a deployment issue. it would be good to improve the deployment scripts or the process.

Thank you anyway. I hope with your PhD is everything fine ;)

**Comment by YuriGlickman** [comment]
Saving works, but  it still adds duplicates of concepts in the editor. Nyree pointed me on this example 
https://policycompass.eu/app/#!/visualizations/114

Please see the attached report as well.
Interesting is that concepts are duplicaed only in the graphical editor and not in  the list of concepts. So, users do not t know which concepts to connect with each other. After saving the model duplicates disappear
Please try to fix it next days
[Sue Nyree Causual model working.docx](https://github.com/policycompass/policycompass/files/439273/Sue.Nyree.Causual.model.working.docx)

**Comment by mohammedbahja** [comment]
Hi @YuriGlickman & @nyreescott, I have fixed this issue in this [PR](https://github.com/policycompass/policycompass-frontend/pull/492).

**Comment by FabiApfelkern** [comment]
@YuriGlickman It is not merged yet. I will do it.

**Comment by FabiApfelkern** [comment]
@YuriGlickman @mohammedbahja It's merged and deployed on alpha

**Comment by mohammedbahja** [comment]
Many thanks, I have tested Nyree's example (https://policycompass.eu/app/#!/visualizations/114)  over the main server and it works fine.

**Comment by YuriGlickman** [comment]
Many thanks. I tested as well.
