### ISSUE TITLE
Add "Added by" to the Model Details

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#649]
Add "Added by" to the Model Details. You have already "Added" and "Modified" fields there
https://policycompass.eu/app/#!/models/20

Here is an example, how it is doen for visualisations:
https://policycompass.eu/app/#!/visualizations/54

**Comment by mohammedbahja** [comment]
@YuriGlickman FCM will not show "Added by" if the user is unknown ( before we apply authentication, unknown users were able to add FCMs ). FCM shows "Added by" if the use exists. 

Example: 
https://policycompass.eu/app/#!/models/100
