### ISSUE TITLE
Integrate carneades front end into Policy Compass

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#65]

**Comment by FabiApfelkern** [comment]
@th0br0 Can we get something here in Sprint 3? An early HTML mockup with no real function would be ok.

**Comment by th0br0** [comment]
Sure, something like that is should be doable.

**Comment by FabiApfelkern** [comment]
@th0br0 Can you give an update on this issue?

**Comment by FabiApfelkern** [comment]
@th0br0 Can you give us an update on this one?
