### ISSUE TITLE
continual Error message when saving a causal model from a data set visualisation

### ISSUE THREAD

**Issue by nyreescott** [policycompass/policycompass#650]
Urgent .
There is a continual error message when a user tries to save a causal model when the user goes straight from the visualisation to the causal model.  Causal model cannot be saved
It is NOT possible to create a causal model at present directly from creating a visualisation.

[error on causal following visualisation 27th july.docx](https://github.com/policycompass/policycompass/files/385728/error.on.causal.following.visualisation.27th.july.docx)

**Comment by mohammedbahja** [comment]
Issues has been already created here. 
policycompass/policycompass/issues/648
