### ISSUE TITLE
502 Bad Gateway in some petitions

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#651]
Sometimes I get the error 502 from the BE server.

If you try to create a visualisation following these steps the error appears:

1. Go to this page
https://policycompass.eu/app/#!/visualizations/create/?datasets=220

2. Click over "Edit Datasets"

3. Search for "FTSE100" into the "Select Datasets" tab

4. Click over the dataset and click "Aply"

5. Click over "Edit Events" and whait (not always happens)

An URL example that retunr error 502 is:
https://services-prod.policycompass.eu/api/v1/visualizationsmanager/visualizations/104

Some screenshoots

![27-07-2016 13-02-20](https://cloud.githubusercontent.com/assets/6602727/17173909/f2082146-53fd-11e6-832a-06e77d359e34.jpg)

![27-07-2016 13-25-35](https://cloud.githubusercontent.com/assets/6602727/17173912/f5756e88-53fd-11e6-9af5-8ad0e65c7b0f.jpg)

![27-07-2016 13-26-10](https://cloud.githubusercontent.com/assets/6602727/17173914/f754c302-53fd-11e6-9839-74fc5f972d36.jpg)

**Comment by slomo** [comment]
Here are the corresponding lines from the nginx log:

```
2016/09/02 10:22:32 [error] 14370#0: *325617 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: services-prod.policycompass.eu, request: "GET /api/v1/visualizationsmanager/visualizations/99 HTTP/1.1", upstream: "http://127.0.0.1:8000/api/v1/visualizationsmanager/visualizations/99", host: "services-prod.policycompass.eu", referrer: "https://policycompass.eu/app/"
2016/09/02 10:22:32 [error] 14370#0: *325621 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: services-prod.policycompass.eu, request: "GET /api/v1/visualizationsmanager/visualizations/102 HTTP/1.1", upstream: "http://127.0.0.1:8000/api/v1/visualizationsmanager/visualizations/102", host: "services-prod.policycompass.eu", referrer: "https://policycompass.eu/app/"
2016/09/02 10:22:32 [error] 14370#0: *325615 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: services-prod.policycompass.eu, request: "GET /api/v1/visualizationsmanager/visualizations/98 HTTP/1.1", upstream: "http://127.0.0.1:8000/api/v1/visualizationsmanager/visualizations/98", host: "services-prod.policycompass.eu", referrer: "https://policycompass.eu/app/"
2016/09/02 10:22:32 [error] 14370#0: *325619 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: services-prod.policycompass.eu, request: "GET /api/v1/visualizationsmanager/visualizations/101 HTTP/1.1", upstream: "http://127.0.0.1:8000/api/v1/visualizationsmanager/visualizations/101", host: "services-prod.policycompass.eu", referrer: "https://policycompass.eu/app/"
```

While policy services seems to report dying workers:

```
[2016-09-02 08:22:32 +0000] [8740] [INFO] Worker exiting (pid: 8740)
[2016-09-02 10:22:32 +0200] [8734] [CRITICAL] WORKER TIMEOUT (pid:8742)
[2016-09-02 08:22:32 +0000] [8739] [INFO] Worker exiting (pid: 8739)
[2016-09-02 08:22:32 +0000] [8742] [INFO] Worker exiting (pid: 8742)
TIME  {'en': 'TIME'}
[2016-09-02 10:22:32 +0200] [17247] [INFO] Booting worker with pid: 17247
[2016-09-02 10:22:32 +0200] [17248] [INFO] Booting worker with pid: 17248
[2016-09-02 10:22:32 +0200] [17249] [INFO] Booting worker with pid: 17249
[2016-09-02 10:22:32 +0200] [17250] [INFO] Booting worker with pid: 17250
```

**Comment by slomo** [comment]
@mmilaprat Could you somehow make this reproducable on stage?

**Comment by mmilaprat** [comment]
Go to this page
https://frontend-stage.policycompass.eu/app/#!/visualizations/create/?datasets=45

Click over "Edit Datasets"

Search for "Test" into the "Select Datasets" tab

Click over the dataset "Dataset from Test Metric" and click "Aply"

Click over "Edit Events" and whait (not always happens)

An URL example that retunr error 502 is:
https://services-stage.policycompass.eu/api/v1/visualizationsmanager/visualizations/41
https://services-stage.policycompass.eu/api/v1/visualizationsmanager/visualizations/42

**Comment by slomo** [comment]
@mmilaprat Thanks that was really helpful

I am not a hundred percent sure, but I would say this is the core issue here:

  - `BaseVisualizationSerializer` has multiple custom fields (eg. `DatasetsField`)
  - those fields are using the BaseAdapter to load data from other services
  - other services here means the same server, which only has 4 workers, meaning 4 requests in parallel

That means two of those request, which each trigger more request, which might even trigger more (I haven't checked) will block the entire server.

- short fix: increase numbers of worker (I just upgraded to 8)
- longterm fix: ???

**Comment by mmilaprat** [comment]
@slomo , at this moment there is a problem in the stage environment (https://frontend-stage.policycompass.eu/app/#!/browse ). 

I don't know if it's related with the increase of number of workers or not (probalby you are working on it doing tests), but the facets (Policy Domains, Locations) are not loaded, also if you try to acces to any item you are redirected to the browse page because comunication to the BE fails.

**Comment by slomo** [comment]
@mmilaprat I was just fixing/debugging this issue, it should now be back online as usual

**Comment by FabiApfelkern** [comment]
@mmilaprat Maybe the solution from @slomo helps already. Otherwise you could change the backend, so it's not using HTTP, but works directly with the database. I tried it for one property, should be very easy: https://github.com/policycompass/policycompass-services/pull/145

**Comment by mmilaprat** [comment]
@FabiApfelkern , are you going to merge your PR?

**Comment by FabiApfelkern** [comment]
No, it was just an example. You have to do decide if you want to do it? Did Yves solution help already?

**Comment by mmilaprat** [comment]
The solution of Yves works in stage, the error disappears but probably I will add your suggestion in a future BE PR.
