### ISSUE TITLE
Cannot save after Editting the dataset

### ISSUE THREAD

**Issue by aquinas9** [policycompass/policycompass#653]
The save button is not activated after editing dataset so the change cannot be saved.
Please check !
![image](https://cloud.githubusercontent.com/assets/10424432/17664339/424c1102-62eb-11e6-932d-17e9cd4f05cd.png)

**Comment by cueneythizli** [comment]
I cannot reproduce this error. For me it's working fine

**Comment by YuriGlickman** [comment]
I can edit my datasets...
If the Save button is deactivated then you are not logged in or it is not your dataset...
or something went wrong... Can you edit you other datasets?

**Comment by aquinas9** [comment]
I found what was the problem. 
I was working on creating dataset but I was automatically logged off(I was using my chrome browser).

Do we have any functionality for this auto- log off?
