### ISSUE TITLE
Replacing "?" Values on FCM following simulation

### ISSUE THREAD

**Issue by nyreescott** [policycompass/policycompass#666]
once a simulation has been run and values have ben obtained from historical data - should the "?" marks on the FCM diagram not be replaced with the values obtained?
[question marks replaced.docx](https://github.com/policycompass/policycompass/files/458862/question.marks.replaced.docx)

**Comment by mohammedbahja** [comment]
This has been fixed in this [PR](policycompass/policycompass-frontend/pull/502)

**Comment by mohammedbahja** [comment]
@nyreescott I have stooped the auto calculation of  concepts' values. As we know, the user needs to add the initial values manually in case the user would like to use the Impact Analysis . The weight calculation can  "only" calculate  weight  values, this is why I was confused about the issue at the beginning, thank you for discovering this. 
I will let you know once @FabiApfelkern merge the changes.
