### ISSUE TITLE
modal configuration window

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#667]
the modal "configuration" window that apperas in the events form when you click over the "configuration" buutton is a bit different from others used in the site. 

![07-09-2016 16-29-41](https://cloud.githubusercontent.com/assets/6602727/18315822/a62c581e-7518-11e6-99b8-1ecdc29d5050.jpg)

probably it must be updated.

**Comment by cueneythizli** [comment]
this modal will be removed with this PR : https://github.com/policycompass/policycompass-frontend/pull/452

**Comment by mmilaprat** [comment]
ok, then I close this issue
