### ISSUE TITLE
Story Manager Improvements

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#672]
- [x]  Cancelbutton, the image is a paper bin, not a cross like other forms (class “fa-trash-o” must be “btn-clear” ?? )
- [x]  Preview button, don’t work
- [ ]  With the Add visualization button you can find and attach visualisations that are in draft
- [x]  As anonymous the button “Login to save” don’t appear.
- [x]  As logged user the button “Save” is disabled until you fulfill all the required fields
- [x]  The required fields don’t have “*”
- [x]  The “?” icon (that appears in other forms) with the help div is missing
- [x]  Into the “chapter title” field, the placeholder text is “Story title” it must be “Chapter title”
- [x]  The “search engine” enable you to link n times the same item (visualization in this case), if you link n times the same visualization the directive don’t work. The same visualization can only be 1 time in the same page.
- [x]  I can only link visualisations and datasets, if I try to link **metrics** I get this message (“Sorry, there is currently no renderer available for this metric.”)
- [x]  I can only link visualisations and datasets, if I try to link **FCM** I get this message (“Sorry, there is currently no renderer available for this fuzzymap.”)
- [x]  If we try to add the same visualisations in different chapters we the visualisations are not loaded correctly
- [x]  When adding a visualization and a dataset into one chapter, the dataset is not displayed in the read view
- [ ]  download button does not work
- [x]  in view mode (/app/#!/stories/3) the main data of the story (Added by, added, modifies,... ) is missing
- [x]  Youtube links is just loading an image, not the video
- [x]  Common fields are missing in both view and edit mode
- [ ]  Adding PC elements should inline them in text
- [ ]  "Add chapter" button could better fit next to tabs and auto-focus the new tab
- [x]  Prevent unauthorised users from entering edit view (by appending /edit to the url, e.g. /app/#!/stories/6/edit)
- [x]  The header icon in the detail view and in edit is missing
- [x]  In the detail page and in edit mode appears the label "username" instead of the real username.
- [x]  If you try to access to a non-existing story you are not redirected to the browse section

**Comment by mmilaprat** [comment]
save button works, but download button not

**Comment by mmilaprat** [comment]
in view mode (/app/#!/stories/3) the main data of the story (Added by, added, modifies,... ) is missing

**Comment by cbotsikas** [comment]
- [ ] Youtube links is just loading an image, not the video
- [ ] Common fields are missing in both view and edit mode
- [ ] Adding PC elements should inline them in text

**Comment by cbotsikas** [comment]
- [ ] "Add chapter" button could better fit next to tabs and auto-focus the new tab

**Comment by michaelalemu** [comment]
- [ ] Prevent unauthorised users from entering edit view (by appending /edit to the url, e.g. /app/#!/stories/6/edit)

**Comment by michaelalemu** [comment]
@FabiApfelkern I was not able to edit your issues therefore I copied all issues here

- [ ]  Cancelbutton, the image is a paper bin, not a cross like other forms (class “fa-trash-o” must be “btn-clear” ?? )
- [ ]  Preview button, don’t work
- [ ]  With the Add visualization button you can find and attach visualisations that are in draft
- [ ]  As anonymous the button “Login to save” don’t appear.
- [ ]  As logged user the button “Save” is disabled until you fulfill all the required fields
- [ ]  The required fields don’t have “*”
- [ ]  The “?” icon (that appears in other forms) with the help div is missing
- [ ]  Into the “chapter title” field, the placeholder text is “Story title” it must be “Chapter title”
- [ ]  The “search engine” enable you to link n times the same item (visualization in this case), if you link n times the same visualization the directive don’t work. The same visualization can only be 1 time in the same page.
- [ ]  I can only link visualisations and datasets, if I try to link metrics and FCM I get this messages (“Sorry, there is currently no renderer available for this metric.” and “Sorry, there is currently no renderer available for this fuzzymap.”)
- [ ]  If we try to add the same visualisations in different chapters we the visualisations are not loaded correctly
- [ ]  When adding a visualization and a dataset into one chapter, the dataset is not displayed in the read view
- [ ]  download button does not work
- [ ]  in view mode (/app/#!/stories/3) the main data of the story (Added by, added, modifies,... ) is missing
- [ ]  Youtube links is just loading an image, not the video
- [ ]  Common fields are missing in both view and edit mode
- [ ]  Adding PC elements should inline them in text
- [ ]  "Add chapter" button could better fit next to tabs and auto-focus the new tab

**Comment by FabiApfelkern** [comment]
@michaelalemu I gave you rights now.

**Comment by mmilaprat** [comment]
In the detail page and in edit mode appears  the label "username" instead of the real username.

![27-09-2016 9-16-43](https://cloud.githubusercontent.com/assets/6602727/18863772/67049dba-8493-11e6-86f2-9b0873539369.jpg)

![27-09-2016 9-16-30](https://cloud.githubusercontent.com/assets/6602727/18863774/6841529a-8493-11e6-8222-4239714af3b2.jpg)

In other items, this type of data is diplayed with other labels

Added by : username
Added: date
Modified: date


example: https://frontend-stage.policycompass.eu/app/#!/datasets/35

**Comment by mmilaprat** [comment]
The header icon in the detail view and in edit is missing, as example a screenshhot of a dataset item.

![27-09-2016 9-24-28](https://cloud.githubusercontent.com/assets/6602727/18863963/436dd8d4-8494-11e6-99d0-76ede3478d13.jpg)

The title of item in stories are different, they are in bold

**Comment by mmilaprat** [comment]
If you try to access to an non-existing story you are not redirected to the browse section

As example:
https://frontend-stage.policycompass.eu/app/#!/stories/800

https://frontend-stage.policycompass.eu/app/#!/stories/48

**Comment by FabiApfelkern** [comment]
@michaelalemu Altough I'm am the creator of a Story I can only "Edit a copy".
