### ISSUE TITLE
What is "howitworks.html"

### ISSUE THREAD

**Issue by slomo** [policycompass/policycompass#675]
Hi,

I am trying to find out what the `app/howitworks.html` does in the frontend repo. Could some one give me a hint?

**Comment by mmilaprat** [comment]
Hi,
In the past the section “How it works” (https://frontend-stage.policycompass.eu/app/#!/i-want-to ) was a “help” section where users can find information about how to use Policy Compass. When the new landing page has been created the section “How it works” or “I want to” has been deleted from the top menu and now it is hidden, probably we must delete the “howtworks.html” page from the repository.

I see that there are 2 howtworks.html pages in PC, one in the “/app/howitworks.html” (the one you said) and the other in “app/modules/common/partials/howItWorks.html” (the one used in the past in the “I want to” section).

I think that  the “/app/howitworks.html” page can be some “backup” file stored by mistake in the repository.

**Comment by FabiApfelkern** [comment]
We don't need it, but it is not bothering.
