### ISSUE TITLE
Entity date Properties alignment

### ISSUE THREAD

**Issue by mohammedbahja** [policycompass/policycompass#676]
Change all modules’ date fields to "date_created" and "date_modified".

**Comment by cbotsikas** [comment]
This issue is blocking https://github.com/policycompass/policycompass/issues/673

**Comment by slomo** [comment]
I added `date_modified` field to metrics. It only makes semi sense (because currently metrics can't be modified). policycompass/policycompass-services#153

**Comment by slomo** [comment]
@mohammedbahja What is the state of this in FCM Manger? If you fixed as well feel free to close the issue.

**Comment by FabiApfelkern** [comment]
FCM is done
https://github.com/policycompass/policycompass-fcmmanager/pull/45
https://github.com/policycompass/policycompass-frontend/pull/521
