### ISSUE TITLE
Active State of Tab Just White

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#68]
I migrated in the bower.json to the new Angular Bootstrap version. This seems to cause a small bug in the tab style. The active state is now only white and the title is not visible.

**Comment by mmilaprat** [comment]
It's solved in the new style?
can you check here:

https://frontend-stage.policycompass.eu/app/

**Comment by FabiApfelkern** [comment]
I checked alreday. It is not. The tabs were not redesigned yet.

**Comment by mmilaprat** [comment]
Hi,
can you tell me the exact Angular Bootstrap version?
and, can you add a screenshot?

**Comment by FabiApfelkern** [comment]
Just check the Bower.json file for the version. I can send you a screenshot later this week but the error is pretty obvious when you are using the tabs eg in the Metrics Manager.

**Comment by mmilaprat** [comment]
please, send me the screenshot because I cannot reproduce the problem

**Comment by FabiApfelkern** [comment]
![screenshot 9](https://cloud.githubusercontent.com/assets/1488424/7832147/0d562fa2-045d-11e5-9220-a0e0b360d99d.png)

Just hover over a Tab.

**Comment by mmilaprat** [comment]
ok, you're right. Sorry, I had misunderstood this issue. I had understood that the tab was white.

**Comment by FabiApfelkern** [comment]
Yes the original bug was a little bit different. The new design changed it.

**Comment by mmilaprat** [comment]
Can you check if the pending pull request of the new UI solves the problem?

**Comment by FabiApfelkern** [comment]
This is fixed with: https://github.com/policycompass/policycompass-frontend/pull/85
