### ISSUE TITLE
"You are not authorized" error message  - on stage 

### ISSUE THREAD

**Issue by mohammedbahja** [policycompass/policycompass#682]
"You are not authorized" error message appears when a user wants to save an FCM. This problem happen ONLY on stage. 

Unauthorized status is throwing from the backend only, based on Adhocracy response as you can see [here](https://github.com/policycompass/policycompass-fcmmanager/blob/master/src/main/java/policycompass/fcmmanager/controllers/FCMModels.java#L987).

<img width="934" alt="1" src="https://cloud.githubusercontent.com/assets/16784021/18966350/ca6794e8-8678-11e6-865c-e885e585d8b0.png">

@FabiApfelkern @slomo If the problem is not from Adhocracy service, could you please check[ this env-entry](https://github.com/policycompass/policycompass-fcmmanager/blob/master/WebContent/WEB-INF/web.xml.template#L50) is correct and accessible on staging server ? 

<img width="891" alt="2" src="https://cloud.githubusercontent.com/assets/16784021/18966602/bfbdf8ec-8679-11e6-9df3-afbcfc95bc2f.png">

**Comment by mohammedbahja** [comment]
I have spotted this, the `deleted:"false"` filed is missing from the stage. 

**Production** 
<img width="1221" alt="2" src="https://cloud.githubusercontent.com/assets/16784021/18972769/618ad218-8692-11e6-8ad0-eac7d32ca904.png">



**Staging** 
<img width="1253" alt="1" src="https://cloud.githubusercontent.com/assets/16784021/18972736/410a6238-8692-11e6-98e7-98423d13a46e.png">


Any explanations ?

**Comment by mohammedbahja** [comment]
@FabiApfelkern may I know the situation on staging? Some other issues appeared on stage. Do we have the same version of stage is deployed on prod ?

**Comment by FabiApfelkern** [comment]
On Stage the latest master is deployed. Prod is far behind.

**Comment by mohammedbahja** [comment]
@FabiApfelkern any update about the FCM back-end on stage ? Also, any update about my comments above regarding "You are not authorized"  ?  

https://fcm-stage.policycompass.eu/api/v1/fcmmanager/models

**Comment by FabiApfelkern** [comment]
@mohammedbahja I have no idea at the moment what is going wrong. I will check this afternoon.

**Comment by FabiApfelkern** [comment]
@mohammedbahja But maybe you understand the error stack?

**Comment by mohammedbahja** [comment]
@FabiApfelkern hmm, I am not sure what it could be however, I think if you take the latest copy of code and rebuild the application it should work. 
I have updated one of the backend files but i did not pushed it yet as I need to know the situation of the Adhocracy missing field `deleted:"false"`. This field is existing on the prod as I mentioned in my comments above and i believe it could be the reason behind throwing the exception of "You are not authorized" on stage.

**Comment by FabiApfelkern** [comment]
@mohammedbahja I don't understand. What field are your referring to?

**Comment by FabiApfelkern** [comment]
@mohammedbahja I rebuild and restarted the server. It works now: https://fcm-stage.policycompass.eu/api/v1/fcmmanager/models/
But can you also check?

**Comment by mohammedbahja** [comment]
@FabiApfelkern yes, the back-end is working now. 
I think some changes in https://adhocracy-frontend-stage.policycompass.eu/api/  has been done. The stage API dose not return the same fields as the production API https://adhocracy-prod.policycompass.eu/api/. 
this field `deleted:"false"` is not returned in the stage API and I think this is why the back-end is throwing "You are not authorized" exception. 


This image from the prod. 

<img width="1261" alt="1" src="https://cloud.githubusercontent.com/assets/16784021/19076546/21ea4b72-8a41-11e6-9556-fe4c26347510.png">

And this image from the stage. 

<img width="1269" alt="2" src="https://cloud.githubusercontent.com/assets/16784021/19076849/4493bf2c-8a42-11e6-9204-ccd971bf8c99.png">

I can deal with this from the back-end but I need to know if any changes going happen in the future to avoid any back-end problems.

**Comment by FabiApfelkern** [comment]
@slomo Can you say something about this?

**Comment by mohammedbahja** [comment]
I hope this [PR](policycompass/policycompass-fcmmanager/pull/46) will deal the issue. However, still wondering about the Adhocracy API in the stage.

**Comment by mohammedbahja** [comment]
@FabiApfelkern @slomo I have just remembered this. earlier you have  suggested to check is user is hidden or deleted, if deleted and hidden then not allow to create fcm. This is why the back-end handling that field. Any way it works now.
