### ISSUE TITLE
User ID created wrongly

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#683]
I don't know what is causing it, but the "Show only my content" checkbox is generating a wrongly formated userID. E.g. https://frontend-stage.policycompass.eu/app/#!/browse?user_id=00000-1
It's just on Stage. So some of the latests PRs might have caused it. Or the new A3 version.

**Comment by cbotsikas** [comment]
It's because Auth.state.userPath is undefined. There was a typo (usetPath) on last authentication refactoring.

**Comment by slomo** [comment]
@cbotsikas thanks
