### ISSUE TITLE
isAdmin is always False

### ISSUE THREAD

**Issue by mmilaprat** [policycompass/policycompass#684]
In stage the "Auth.state.isAdmin" is always false

**Comment by cbotsikas** [comment]
@mmilaprat maybe you are not admin on stage. According to the god list on stage only the following three accounts are admins:
[admin (0000000)](https://adhocracy-frontend-stage.policycompass.eu/api/principals/users/0000000/)
[miquel.mila.admin (0000043)](https://adhocracy-frontend-stage.policycompass.eu/api/principals/users/0000043/)
[fki (0000005)](https://adhocracy-frontend-stage.policycompass.eu/api/principals/users/0000005/)

I think your account is [miquel.mila (0000001)](https://adhocracy-frontend-stage.policycompass.eu/api/principals/users/0000001), isn't it?

@slomo @MagdaN Is is possible that with the latest changes on adhocracy the list was reset?

**Comment by FabiApfelkern** [comment]
@cbotsikas We discussed it in the telco. It's most likely a bug in a3. Miquel was talking about his admin user name.

**Comment by mmilaprat** [comment]
I have 2 users. miquel.mila and miquel.mila.admin. 
miquel.mila is an end user but miquel.mila.admin is an admin user, I always recive that isAdmin is false with miquel.mila.admin

**Comment by slomo** [comment]
I fixed it for the affected accounts, I will never-the-less add pull-request for solving this issue in principal.

**Comment by fabiankirstein** [comment]
See: https://github.com/policycompass/policycompass/issues/687
