### ISSUE TITLE
Auth for Admins/God inconsistent

### ISSUE THREAD

**Issue by fabiankirstein** [policycompass/policycompass#687]
@slomo I just want some clarification who the admin authorization is working now. Is it "god"? Is it "admin".  On Alpha it is not working at the moment.

@mohammedbahja I have the feeling that FCMs can be edited by everybody. Can you please check?

**Comment by mohammedbahja** [comment]
@FabiApfelkern I have tested, and canot be edited by others. Just the creators can edit their won FCMs

**Comment by fabiankirstein** [comment]
@mohammedbahja On which server have you tested it?

**Comment by slomo** [comment]
Currently we consider all users to be admin, that have the role `admin` assigned. On stage those are all users you gave me earlier. On prod there are probably no users with that role.

**Comment by fabiankirstein** [comment]
So this needs to reflected then in A3 on the Alpha server? And I guess FCM does not have it in the backend yet?

**Comment by mohammedbahja** [comment]
@FabiApfelkern I tested the production. Please see the image below. This is for the scenario when a user tries to edit other users models. 
<img width="756" alt="1" src="https://cloud.githubusercontent.com/assets/16784021/19228938/a3a3a8b4-8ec1-11e6-96f6-1d28acf750b1.png">

**Comment by fabiankirstein** [comment]
Ok. Thanks!

**Comment by slomo** [comment]
I fixed this for fcm and update uses on all deployments https://github.com/policycompass/policycompass-fcmmanager/pull/47
