### ISSUE TITLE
Login/Signup header is not consistent to the rest

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#693]
![image](https://cloud.githubusercontent.com/assets/1640100/19381889/006f92e4-91fe-11e6-8815-d000e5c93e29.png)

![image](https://cloud.githubusercontent.com/assets/1640100/19381908/173b8f14-91fe-11e6-8765-4f1b646aa73d.png)

![image](https://cloud.githubusercontent.com/assets/1640100/19382002/83068226-91fe-11e6-9af1-e6970abf754e.png)

Also, "Registration completed.Check your email for the activation link and proceed to" highlights on mouse over like a link.

**Comment by slomo** [comment]
@cbotsikas I adopted the design a bit, it should be available on stage soon. Could you check if your remarks where addressed and close, if so?

**Comment by slomo** [comment]
I just realised that it is not clear: What is the supposed header in policycompass?

![](http://image.prntscr.com/image/19bdac1393a44a85a164de4b336ef6a4.png)

![](http://image.prntscr.com/image/055843b4c6134b3197d84043b6028f85.png)

![](http://image.prntscr.com/image/4cc45158ff82412b9dbe8d44a4acf189.png)

The existing style was comparable to datasets, the new one is more like the story manager:

![](http://image.prntscr.com/image/dd839d4c20f64c28ab98728849e57c51.png)
