### ISSUE TITLE
Activation page

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#694]
![image](https://cloud.githubusercontent.com/assets/1640100/19382087/eaa69894-91fe-11e6-9142-d72ca05dd028.png)

Can you add Policy Compass Logo and link to the platform? Maybe users have already closed the registration page so the statement "You can now close this tab and go back to Policy Compass" is not applicable.

**Comment by slomo** [comment]
This is the standard activation page if A3 is in embed mode. Since it doesn't know where it is embedded and it could be even embedded in multiple sites, it can't offer a link back and instead has this clutch with closing the tab.

Unless this is super important, I'd like to not fix this issue.
