### ISSUE TITLE
Activation link wasn't send / Password reset

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#695]
If new users didn't receive the activation link, how can this be sent again?

Also, Is there any option to reset a forgotten password?

**Comment by fabiankirstein** [comment]
@cbotsikas Was it actually not send or are you asking for the option for resending?

**Comment by cbotsikas** [comment]
It was reported to me that a user did not receive the activation link on a gmail mail. There should also be a feedback from that user.

I'm asking for the option to reset forgotten passwords (I can't find such option anywhere) and the ability to request the activation link again.

**Comment by slomo** [comment]
I added an ui for password reset in https://github.com/policycompass/policycompass-frontend/pull/555
