### ISSUE TITLE
Frontend Loading Indicator

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#73]

**Comment by mmilaprat** [comment]
there is this possibility:

<div class="loading-container">
        <div class="loading"></div>
        <div id="loading-text">loading</div>
</div>

It is used in visualisations. Are you refereing to use something like this?

**Comment by FabiApfelkern** [comment]
Yes in this direction. But I was think about a more global one. More like e.g. YouTube has it on the top of the site.

**Comment by mmilaprat** [comment]
we can check the ngprogress directive (http://victorbjelkholm.github.io/ngProgress/ )

**Comment by mmilaprat** [comment]
In the pull request of the new UI there is a loading indicator

**Comment by FabiApfelkern** [comment]
The Loading Indicator looks very good so far. We have to evaluate in more in action during the next weeks. However it does not t cover yet the initial loading of the page, because the indicator itself is not loaded in this moment. But we can work on it later.

**Comment by FabiApfelkern** [comment]
I think a intitial loader is in work in progress. Can we put this to Sprint 3?
