### ISSUE TITLE
As an external application, I want to add content through the API

### ISSUE THREAD

**Issue by rukala** [policycompass/policycompass#82]
We need to be able to authenticate external applications (i.e. PolicyCompass services) in order to:

- Allow Carneades to add arguments map to existing discussion resources (for user story `DS4ff`).
- Allow other services (Metrics, Visualization, FCM...) create discussion topic resources (instead of doing the same from the frontend through the ad-hoc `ExternalResource` hack)

A rather simple solution would be to add a special user type "app" which can create "persistent session" tokens, which are then set in the config of the external apps.

**Comment by MagdaN** [comment]
We will evaluate if this is necessary on our meeting in Madrid.

**Comment by slomo** [comment]
Any out comes here from the meeting in Madrid?

**Comment by FabiApfelkern** [comment]
We haven't talked about actually. @YuriGlickman What do you think? Is that something we need?

**Comment by slomo** [comment]
@FabiApfelkern @YuriGlickman Any news here?

**Comment by slomo** [comment]
Closing since old
