### ISSUE TITLE
As a user, I want to list all discussions in a central place

### ISSUE THREAD

**Issue by rukala** [policycompass/policycompass#84]
PCompass discussions are currently spread around the platform.

In year 2, `ExternalResources` need to be searchable (#81) and listed in a central place, categorized by the item type they refer to (metric, visualization, fcm).

They should also include a URL to the referer object.

Open question: How to display in list what this discussion refers to? Just a URL is not really useful.

Options:

- Preview of the refered-to object  - what about iframe in iframe? ;)
- Store title with the URL in A3 (maybe always update on change throug #1740) - sounds good.

**Comment by nadiapo** [comment]
Discussions will be listed under a new menu item called Discussions

**Comment by nidico** [comment]
We discussed that task at LIQD and wondered what the intention is, as basically such a list already exists, namely the main PolicyCompass *browse* screen - all of the listed items shall be discussable. Adding an additional list which basically shows the same items might be confusing to users. In addition, if that central place would list discussions in a purely forum-style way, the discussions would be discoupled of the actual content which is being discussed.

So we wondered if we couldn't achieve a better effect and less duplication if we just added the number of discussions in the browse list besides the rating widget - ![icon-number-discussions](https://cloud.githubusercontent.com/assets/457147/9731182/c3bbc24c-561b-11e5-8d8e-ad586030adee.png) - and optionally add a facet *has discussion* (#138).

Doing this could be done by either (from fast to slow):

- pushing the number of discussions to Elasticsearch (which would also allow the faceting)
- querying the adhocracy backend for each entry (not hard to do)
- embedding the comment indicator (slow).

Any opinions?

**Comment by FabiApfelkern** [comment]
I think it is a good idea to have in embedded in the search based on Elasticsearch. But still I think it is good to have somehow a dedicated discussion page. At least with the top or most recent discussion. You could place a link to the concerning entity (Metric, Event,..) behind each discussion.

**Comment by nidico** [comment]
The plan is to do the following:

- [ ] Add rating count to item index (by extending `searchmanager.index_utils`
- [ ] Index item after commenting an `IExternalResource` object (by extending the Adhocracy backend)
- [ ] Show comment count in pcompass search frontend (by extending the pcompass search angular module)

**Comment by nidico** [comment]
This is done. Proper theming can be done in a separate issue.
