### ISSUE TITLE
As a user, I want to request new metrics, visualizations and FCMs

### ISSUE THREAD

**Issue by rukala** [policycompass/policycompass#85]
I'd propose to

- create a new resource type `Request`,
- which is basically just a renamed simple proposal (title, description; commentable, supportable).

No further semantics is attached. In the comments, users can then post links to their creations.

This is more important than #84.

**Comment by nidico** [comment]
This has started in policycompass/policycompass-frontend#180, but still needs some polishing.

**Comment by nidico** [comment]
This is already done.
