### ISSUE TITLE
Implement proper metrics editing / copying with auth

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#90]
Only the creator or an admin shall be able to edit metrics.

In order to do this use session validation as described [in the wiki](https://github.com/policycompass/policycompass/wiki/Auth-Service).

**Comment by nadiapo** [comment]
As discussed in the meeting, all content in PC will be editable. If the user editing is not the owner of the content, when saving, new metdata will need to be provided by the user so that content will be saved as new.

**Comment by nidico** [comment]
We'll use this as an example how to use the auth service in both backend and frontend.

**Comment by nidico** [comment]
We discussed in today's telco:

- As long as a metric has not been operationalized, it can be edited by the creator; after operationalization not anymore.
- It can always be copied to a new metric by anybody.

On copy, we should add a link to the metrics metadata which states from which metric it has been derived and display both directions in the metrics detail UI.

**Comment by MagdaN** [comment]
I implemented a simple editing in the first iteration (admin and owners can edit all fields of a metric, the edit button on the detail page is only visible to users with edit rights) - the more advanced features (edit only possible when metric has not been operationalized, enable copy) I will do in the next iteration. See here: https://github.com/policycompass/policycompass-frontend/pull/279

**Comment by slomo** [comment]
Fixed this by making metrics editable for everyone.
