### ISSUE TITLE
Document how to use Auth service

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#91]
Current documentation is here: https://github.com/policycompass/policycompass/wiki/Auth-Service

This should be extended by:

- What *excactly* do the backend services need to call and check for in order to find out whether a token is valid and to which role a user belongs?
- What does the frontend need to do in order to check whether a user is logged in or is admin? (Will be used by #121)
- How to add users to a certain role (in particular `admin`)?

**Comment by nidico** [comment]
Updated the description as discussed in Cambridge. Bump to sprint 2.

**Comment by nidico** [comment]
The [Auth Service](https://github.com/policycompass/policycompass/wiki/Auth-Service) wiki page has been updated to cover these topics.

In short:

- Backend services should perform a single request on `POST` or `PUT` requests, which [verifies the session and checks the user role at once](https://github.com/policycompass/policycompass/wiki/Auth-Service#bonus-verify-session-token-and-check-for-admin-role-at-once)

- Frontend angular modules should inject the `Auth` service and directly use or watch `Auth.state` (once #160 has been merged).

**Comment by mmilaprat** [comment]
About the front end. I checked the content of the header.html to know how to recover the user data and I have a question.

I see that in the header.html we use the controller "UserState", but it is just used in the tag header. If we need to get the user information to show/hide any button (like edit/delete) we need to add this contoller in our "container"? the controller "UserData" can be placed in another place? the "body"? Then we can use the "authState" variable to the entire page.

or probably I didn't understand correctly how to use the authorization in the front end.

**Comment by FabiApfelkern** [comment]
I agree. We should go over this topic later in the telko to make sure we are all on the same page.
