### ISSUE TITLE
Improve "How it Works" 

### ISSUE THREAD

**Issue by nadiapo** [policycompass/policycompass#98]

**Comment by nadiapo** [comment]
Revision of explanatory text; make it more readable, understandable
Use parallax.js for scroll effects

**Comment by FabiApfelkern** [comment]
@nadiapo We should at least update it to the new methodology.

**Comment by nadiapo** [comment]
Yes, this needs to be revised, but Focus is responsible for this

**Comment by FabiApfelkern** [comment]
This is part of the new landing page.
