### ISSUE TITLE
Create I want to wizard

### ISSUE THREAD

**Issue by nadiapo** [policycompass/policycompass#99]
Based on 
http://policy.atosresearch.eu/want.html
http://policy.atosresearch.eu/want2.php

**Comment by mmilaprat** [comment]
a new directive has been created to add this functionality.

Probably the help texts and links must be updated, but the functionality can be checked.

A new pull request is in the fork https://github.com/bullz/policycompass-frontend

**Comment by nadiapo** [comment]
need to revise each step, help text and initial screens

**Comment by nadiapo** [comment]
Will revise by next Sprint with a more stable version of the functionalities

**Comment by FabiApfelkern** [comment]
@nadiapo Can we put this to Sprint 5?

**Comment by FabiApfelkern** [comment]
What is the status of that one?

**Comment by nadiapo** [comment]
We have updated it, but there are still many gaps to cover with missing functionality. Need to improve after the review.

**Comment by nadiapo** [comment]
Funcionality no longer exists - replaced by new homepage
